"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, HelpCircle, LoaderCircle, MessageSquareQuote, Plus, Star } from "lucide-react";
import { collectionFromApi } from "@/lib/api-response";

type Status = "ACTIVE" | "INACTIVE";
type Faq = { id: number; question: string; answer: string; sortOrder: number; status: Status };
type FaqCategory = { id: number; name: string; sortOrder: number; status: Status; faqs: Faq[] };
type Testimonial = { id: number; name: string; title: string | null; quote: string; stars: number; status: Status };
type EnquiryStatus = "NEW" | "IN_PROGRESS" | "RESOLVED";
type Enquiry = { id: number; type: string; name: string; email: string | null; phone: string | null; subject: string | null; message: string; status: EnquiryStatus; createdAt: string };
const inputClass = "mt-2 h-10 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
const enquiryTone: Record<EnquiryStatus, string> = { NEW: "bg-accent-tint text-accent-tint-ink", IN_PROGRESS: "bg-neutral-tint text-ink-muted", RESOLVED: "bg-positive-tint text-positive-tint-ink" };

export function SupportContentListing() {
  const [tab, setTab] = useState<"faqs" | "testimonials" | "enquiries">("faqs");
  const [categories, setCategories] = useState<FaqCategory[]>([]), [testimonials, setTestimonials] = useState<Testimonial[]>([]), [enquiries, setEnquiries] = useState<Enquiry[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState("");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [categoriesRes, testimonialsRes, enquiriesRes] = await Promise.all([fetch("/api/faq-categories", { cache: "no-store" }), fetch("/api/testimonials", { cache: "no-store" }), fetch("/api/enquiries?page=1&perPage=50", { cache: "no-store" })]);
      const categoriesPayload = await categoriesRes.json(); if (!categoriesRes.ok) throw new Error(apiMessage(categoriesPayload, "FAQs could not be loaded.")); setCategories(collectionFromApi<FaqCategory>(categoriesPayload));
      const testimonialsPayload = await testimonialsRes.json().catch(() => ({})); if (testimonialsRes.ok) setTestimonials(collectionFromApi<Testimonial>(testimonialsPayload));
      const enquiriesPayload = await enquiriesRes.json().catch(() => ({})); if (enquiriesRes.ok) setEnquiries(collectionFromApi<Enquiry>(enquiriesPayload));
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Support content could not be loaded."); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  async function updateEnquiry(id: number, status: EnquiryStatus) { try { const response = await fetch(`/api/enquiries/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (!response.ok) throw new Error(apiMessage(await response.json().catch(() => ({})), "Enquiry could not be updated.")); await load(); } catch (updateError) { setError(updateError instanceof Error ? updateError.message : "Enquiry could not be updated."); } }

  return <div className="w-full"><h1 className="text-[22px] font-semibold tracking-[-0.01em] text-ink">FAQs &amp; support</h1><p className="mt-1 text-[13.5px] text-ink-muted">Help centre content, customer testimonials, and contact enquiries.</p>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <div className="mt-5 flex gap-1 border-b border-border">{([{ id: "faqs", label: "FAQs" }, { id: "testimonials", label: "Testimonials" }, { id: "enquiries", label: `Enquiries (${enquiries.filter((e) => e.status === "NEW").length})` }] as const).map((item) => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`relative px-3 py-2.5 text-[13px] font-semibold ${tab === item.id ? "text-ink after:absolute after:inset-x-1 after:bottom-0 after:h-0.5 after:bg-ink" : "text-ink-muted hover:text-ink"}`}>{item.label}</button>)}</div>
  {loading ? <div className="flex min-h-40 items-center justify-center"><LoaderCircle className="h-5 w-5 animate-spin text-ink-muted" /></div> : tab === "faqs" ? <FaqsTab categories={categories} onChanged={load} /> : tab === "testimonials" ? <TestimonialsTab testimonials={testimonials} onChanged={load} /> : <section className="mt-4 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="bg-canvas text-[10.5px] uppercase tracking-[0.06em] text-ink-muted"><tr><th className="px-4 py-3 font-semibold">From</th><th className="px-4 py-3 font-semibold">Type</th><th className="px-4 py-3 font-semibold">Message</th><th className="px-4 py-3 font-semibold">Received</th><th className="px-4 py-3 text-center font-semibold">Status</th></tr></thead><tbody className="divide-y divide-border">{enquiries.map((enquiry) => <tr key={enquiry.id} className="hover:bg-canvas"><td className="px-4 py-3"><p className="text-[13px] font-semibold text-ink">{enquiry.name}</p><p className="mt-0.5 text-[10.5px] text-ink-muted">{enquiry.email ?? enquiry.phone ?? "—"}</p></td><td className="px-4 py-3 text-xs text-ink-secondary">{enquiry.type}</td><td className="max-w-sm px-4 py-3"><p className="line-clamp-2 text-xs text-ink-muted">{enquiry.subject ? `${enquiry.subject}: ` : ""}{enquiry.message}</p></td><td className="px-4 py-3 text-xs text-ink-secondary">{new Date(enquiry.createdAt).toLocaleDateString("en-GB")}</td><td className="px-4 py-3 text-center"><select value={enquiry.status} onChange={(event) => void updateEnquiry(enquiry.id, event.target.value as EnquiryStatus)} className={`rounded-full border-0 px-2 py-1 text-[10.5px] font-semibold outline-none ${enquiryTone[enquiry.status]}`}><option value="NEW">New</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select></td></tr>)}{!enquiries.length ? <tr><td colSpan={5} className="h-32 text-center text-[13px] text-ink-muted">No enquiries yet.</td></tr> : null}</tbody></table></div></section>}
  </div>;
}

function FaqsTab({ categories, onChanged }: { categories: FaqCategory[]; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(""), [savingCategory, setSavingCategory] = useState(false), [error, setError] = useState("");
  async function addCategory(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; setSavingCategory(true); setError(""); try { const response = await fetch("/api/faq-categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), sortOrder: categories.length }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "FAQ category could not be created.")); setName(""); await onChanged(); } catch (addError) { setError(addError instanceof Error ? addError.message : "FAQ category could not be created."); } finally { setSavingCategory(false); } }
  return <div className="mt-4">{error ? <p className="mb-3 text-xs text-danger-tint-ink">{error}</p> : null}<form onSubmit={(event) => void addCategory(event)} className="flex items-end gap-2 rounded-xl border border-border bg-surface p-3.5 shadow-card"><label className="flex-1 text-[13px] font-semibold text-ink-secondary">New category<input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Orders & delivery" className={inputClass} /></label><button type="submit" disabled={savingCategory || !name.trim()} className="inline-flex h-10 items-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{savingCategory ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Add</button></form>
  <div className="mt-4 space-y-4">{categories.map((category) => <FaqCategoryCard key={category.id} category={category} onChanged={onChanged} />)}{!categories.length ? <p className="rounded-xl border border-border bg-surface p-8 text-center text-[13px] text-ink-muted shadow-card">No FAQ categories yet.</p> : null}</div></div>;
}

function FaqCategoryCard({ category, onChanged }: { category: FaqCategory; onChanged: () => Promise<void> }) {
  const [question, setQuestion] = useState(""), [answer, setAnswer] = useState(""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function addFaq(event: FormEvent) { event.preventDefault(); if (!question.trim() || !answer.trim()) return; setSaving(true); setError(""); try { const response = await fetch(`/api/faq-categories/${category.id}/faqs`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: question.trim(), answer: answer.trim(), sortOrder: category.faqs.length }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "FAQ could not be added.")); setQuestion(""); setAnswer(""); await onChanged(); } catch (addError) { setError(addError instanceof Error ? addError.message : "FAQ could not be added."); } finally { setSaving(false); } }
  return <div className="overflow-hidden rounded-xl border border-border bg-surface shadow-card"><div className="flex items-center gap-2.5 border-b border-border p-4"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><HelpCircle className="h-4 w-4" /></span><h3 className="text-[13.5px] font-semibold text-ink">{category.name}</h3></div><div className="divide-y divide-border">{category.faqs.map((faq) => <div key={faq.id} className="p-4"><p className="text-[13px] font-semibold text-ink">{faq.question}</p><p className="mt-1 text-xs leading-5 text-ink-muted">{faq.answer}</p></div>)}{!category.faqs.length ? <p className="p-4 text-xs text-ink-muted">No FAQs in this category yet.</p> : null}</div><form onSubmit={(event) => void addFaq(event)} className="border-t border-border bg-canvas p-3.5">{error ? <p className="mb-2 text-xs text-danger-tint-ink">{error}</p> : null}<input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Question" className="h-9 w-full rounded-md border border-border-strong bg-surface px-3 text-xs outline-none focus:border-accent-strong" /><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Answer" rows={2} className="mt-2 w-full resize-y rounded-md border border-border-strong bg-surface px-3 py-2 text-xs outline-none focus:border-accent-strong" /><button type="submit" disabled={saving || !question.trim() || !answer.trim()} className="mt-2 inline-flex h-8 items-center gap-1.5 rounded-md bg-ink px-3 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" /> : <Plus className="h-3.5 w-3.5" />}Add FAQ</button></form></div>;
}

function TestimonialsTab({ testimonials, onChanged }: { testimonials: Testimonial[]; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(""), [title, setTitle] = useState(""), [quote, setQuote] = useState(""), [stars, setStars] = useState(5), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim() || !quote.trim()) return; setSaving(true); setError(""); try { const response = await fetch("/api/testimonials", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), title: title.trim() || undefined, quote: quote.trim(), stars, sortOrder: testimonials.length }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Testimonial could not be created.")); setName(""); setTitle(""); setQuote(""); setStars(5); await onChanged(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Testimonial could not be created."); } finally { setSaving(false); } }
  return <div className="mt-4">{error ? <p className="mb-3 text-xs text-danger-tint-ink">{error}</p> : null}<form onSubmit={(event) => void submit(event)} className="rounded-xl border border-border bg-surface p-4 shadow-card"><div className="grid gap-3 sm:grid-cols-2"><label className="text-[13px] font-semibold text-ink-secondary">Name<input value={name} onChange={(event) => setName(event.target.value)} className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">Title (optional)<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Verified buyer" className={inputClass} /></label></div><label className="mt-3 block text-[13px] font-semibold text-ink-secondary">Quote<textarea value={quote} onChange={(event) => setQuote(event.target.value)} rows={2} className="mt-2 w-full resize-y rounded-md border border-border-strong bg-surface px-3 py-2 text-[13px] outline-none focus:border-accent-strong" /></label><label className="mt-3 block text-[13px] font-semibold text-ink-secondary">Rating<select value={stars} onChange={(event) => setStars(Number(event.target.value))} className={`${inputClass} w-32`}>{[5, 4, 3, 2, 1].map((value) => <option key={value} value={value}>{value} star{value > 1 ? "s" : ""}</option>)}</select></label><button type="submit" disabled={saving || !name.trim() || !quote.trim()} className="mt-3 inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Add testimonial</button></form>
  <div className="mt-4 grid gap-3 sm:grid-cols-2">{testimonials.map((testimonial) => <div key={testimonial.id} className="rounded-xl border border-border bg-surface p-4 shadow-card"><div className="flex items-center gap-1 text-amber-500">{Array.from({ length: testimonial.stars }).map((_, i) => <Star key={i} className="h-3.5 w-3.5 fill-current" />)}</div><p className="mt-2 text-xs leading-5 text-ink-secondary">&ldquo;{testimonial.quote}&rdquo;</p><p className="mt-2 text-[11.5px] font-semibold text-ink">{testimonial.name}{testimonial.title ? <span className="font-normal text-ink-muted"> · {testimonial.title}</span> : null}</p></div>)}{!testimonials.length ? <p className="rounded-xl border border-border bg-surface p-8 text-center text-[13px] text-ink-muted shadow-card sm:col-span-2"><MessageSquareQuote className="mx-auto mb-2 h-6 w-6 text-ink-faint" />No testimonials yet.</p> : null}</div></div>;
}
