"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useRef, useState } from "react";
import NextImage from "next/image";
import { AlertTriangle, BadgeCheck, Image as ImageIcon, LoaderCircle, Megaphone, Plus, Sparkles, Trash2, Upload } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { collectionFromApi } from "@/lib/api-response";
import { mediaFileUrl, type MediaItem } from "@/lib/media";

type Status = "ACTIVE" | "INACTIVE";
type Tone = "VIOLET" | "ELECTRIC" | "CYAN" | "CRIMSON";
type HeroSlide = { id: number; eyebrow: string | null; headline: string; subheading: string | null; image: string | null; imagePosition: string | null; tone: Tone; ctaLabel: string | null; ctaUrl: string | null; secondaryCtaLabel: string | null; secondaryCtaUrl: string | null; sortOrder: number; status: Status };
const toneOptions: { value: Tone; label: string }[] = [{ value: "VIOLET", label: "Violet" }, { value: "ELECTRIC", label: "Electric blue" }, { value: "CYAN", label: "Cyan" }, { value: "CRIMSON", label: "Crimson" }];
type TrustBadge = { id: number; label: string; icon: string | null; sortOrder: number };
type LinkType = "PRODUCT" | "CATEGORY" | "BRAND" | "CUSTOM_URL";
type Banner = { id: number; title: string; slug: string; linkType: LinkType; productId: number | null; categoryId: number | null; brandId: number | null; customUrl: string | null; position: string; displayOrder: number; status: Status };
type SectionType = "NEWLY_ADDED" | "FEATURED" | "BEST_SELLER" | "TOP_RATED" | "MANUAL";
type FeaturedSection = { id: number; title: string; slug: string; sectionType: SectionType; categoryId: number | null; sortOrder: number; status: Status; manualProducts: { productId: number }[] };
const inputClass = "mt-2 h-10 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
function statusBadge(status: Status) { return <span className={`inline-flex rounded-full px-2 py-0.5 text-[10.5px] font-semibold ${status === "ACTIVE" ? "bg-positive-tint text-positive-tint-ink" : "bg-neutral-tint text-ink-muted"}`}>{status}</span>; }

export function MerchandisingListing() {
  const [tab, setTab] = useState<"hero" | "banners" | "sections">("hero");
  const [slides, setSlides] = useState<HeroSlide[]>([]), [badges, setBadges] = useState<TrustBadge[]>([]);
  const [banners, setBanners] = useState<Banner[]>([]), [sections, setSections] = useState<FeaturedSection[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [slideEditing, setSlideEditing] = useState<HeroSlide | "new" | null>(null);
  const [bannerEditing, setBannerEditing] = useState<Banner | "new" | null>(null);
  const [sectionEditing, setSectionEditing] = useState<FeaturedSection | "new" | null>(null);
  const [deleteSlide, setDeleteSlide] = useState<HeroSlide | null>(null), [deleteBanner, setDeleteBanner] = useState<Banner | null>(null), [deleteSection, setDeleteSection] = useState<FeaturedSection | null>(null);
  const [deleting, setDeleting] = useState(false);

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [slidesRes, badgesRes, bannersRes, sectionsRes] = await Promise.all([fetch("/api/hero-slides", { cache: "no-store" }), fetch("/api/hero-trust-badges", { cache: "no-store" }), fetch("/api/banners", { cache: "no-store" }), fetch("/api/featured-sections", { cache: "no-store" })]);
      const slidesPayload = await slidesRes.json(); if (!slidesRes.ok) throw new Error(apiMessage(slidesPayload, "Hero slides could not be loaded.")); setSlides(collectionFromApi<HeroSlide>(slidesPayload));
      const badgesPayload = await badgesRes.json().catch(() => ({})); if (badgesRes.ok) setBadges(collectionFromApi<TrustBadge>(badgesPayload));
      const bannersPayload = await bannersRes.json().catch(() => ({})); if (bannersRes.ok) setBanners(collectionFromApi<Banner>(bannersPayload));
      const sectionsPayload = await sectionsRes.json().catch(() => ({})); if (sectionsRes.ok) setSections(collectionFromApi<FeaturedSection>(sectionsPayload));
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Merchandising data could not be loaded."); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  async function removeSlide() { if (!deleteSlide) return; setDeleting(true); try { const response = await fetch(`/api/hero-slides/${deleteSlide.id}`, { method: "DELETE" }); if (!response.ok && response.status !== 204) throw new Error(apiMessage(await response.json().catch(() => ({})), "Slide could not be deleted.")); setDeleteSlide(null); await load(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Slide could not be deleted."); } finally { setDeleting(false); } }
  async function removeBanner() { if (!deleteBanner) return; setDeleting(true); try { const response = await fetch(`/api/banners/${deleteBanner.id}`, { method: "DELETE" }); if (!response.ok && response.status !== 204) throw new Error(apiMessage(await response.json().catch(() => ({})), "Banner could not be deleted.")); setDeleteBanner(null); await load(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Banner could not be deleted."); } finally { setDeleting(false); } }
  async function removeSection() { if (!deleteSection) return; setDeleting(true); try { const response = await fetch(`/api/featured-sections/${deleteSection.id}`, { method: "DELETE" }); if (!response.ok && response.status !== 204) throw new Error(apiMessage(await response.json().catch(() => ({})), "Featured section could not be deleted.")); setDeleteSection(null); await load(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Featured section could not be deleted."); } finally { setDeleting(false); } }

  return <div className="w-full"><h1 className="text-[22px] font-semibold tracking-[-0.01em] text-ink">Merchandising</h1><p className="mt-1 text-[13.5px] text-ink-muted">Homepage hero, promotional banners and featured product rails.</p>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <div className="mt-5 flex gap-1 border-b border-border">{([{ id: "hero", label: "Hero" }, { id: "banners", label: "Banners" }, { id: "sections", label: "Featured sections" }] as const).map((item) => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`relative px-3 py-2.5 text-[13px] font-semibold ${tab === item.id ? "text-ink after:absolute after:inset-x-1 after:bottom-0 after:h-0.5 after:bg-ink" : "text-ink-muted hover:text-ink"}`}>{item.label}</button>)}</div>
  {loading ? <div className="flex min-h-40 items-center justify-center"><LoaderCircle className="h-5 w-5 animate-spin text-ink-muted" /></div> : tab === "hero" ? <>
    <div className="mt-4 flex justify-end"><button type="button" onClick={() => setSlideEditing("new")} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-3.5 text-xs font-semibold text-white hover:bg-[#1d2939]"><Plus className="h-4 w-4" />Add slide</button></div>
    <section className="mt-3 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><div className="divide-y divide-border">{slides.map((slide) => <div key={slide.id} className="flex items-center gap-3 p-4">{slide.image ? <NextImage unoptimized src={slide.image.startsWith("/uploads/") ? mediaFileUrl(slide.image) : slide.image} width={56} height={36} alt="" className="h-9 w-14 shrink-0 rounded-md object-cover" /> : <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><ImageIcon className="h-4 w-4" /></span>}<div className="min-w-0 flex-1">{slide.eyebrow ? <p className="text-[10.5px] font-semibold uppercase tracking-[0.06em] text-ink-faint">{slide.eyebrow}</p> : null}<p className="text-[13px] font-semibold text-ink">{slide.headline}</p><p className="mt-0.5 truncate text-xs text-ink-muted">{slide.subheading ?? "—"}{slide.ctaLabel ? ` · CTA: ${slide.ctaLabel}` : ""}</p></div>{statusBadge(slide.status)}<button type="button" onClick={() => setSlideEditing(slide)} className="h-8 rounded-md border border-border px-3 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint">Edit</button><button type="button" onClick={() => setDeleteSlide(slide)} aria-label={`Delete ${slide.headline}`} className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted hover:bg-danger-tint hover:text-danger-tint-ink"><Trash2 className="h-4 w-4" /></button></div>)}{!slides.length ? <p className="p-6 text-center text-[13px] text-ink-muted">No hero slides yet.</p> : null}</div></section>
    <h2 className="mt-6 text-[14px] font-semibold text-ink">Trust badges</h2>
    <TrustBadgesEditor badges={badges} onSaved={load} />
  </> : tab === "banners" ? <>
    <div className="mt-4 flex justify-end"><button type="button" onClick={() => setBannerEditing("new")} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-3.5 text-xs font-semibold text-white hover:bg-[#1d2939]"><Plus className="h-4 w-4" />Add banner</button></div>
    <section className="mt-3 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><div className="divide-y divide-border">{banners.map((banner) => <div key={banner.id} className="flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><Megaphone className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-[13px] font-semibold text-ink">{banner.title}</p><p className="mt-0.5 text-xs text-ink-muted">{banner.position} · {banner.linkType.replace("_", " ").toLowerCase()}</p></div>{statusBadge(banner.status)}<button type="button" onClick={() => setBannerEditing(banner)} className="h-8 rounded-md border border-border px-3 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint">Edit</button><button type="button" onClick={() => setDeleteBanner(banner)} aria-label={`Delete ${banner.title}`} className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted hover:bg-danger-tint hover:text-danger-tint-ink"><Trash2 className="h-4 w-4" /></button></div>)}{!banners.length ? <p className="p-6 text-center text-[13px] text-ink-muted">No banners yet.</p> : null}</div></section>
  </> : <>
    <div className="mt-4 flex justify-end"><button type="button" onClick={() => setSectionEditing("new")} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-3.5 text-xs font-semibold text-white hover:bg-[#1d2939]"><Plus className="h-4 w-4" />Add section</button></div>
    <section className="mt-3 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><div className="divide-y divide-border">{sections.map((section) => <div key={section.id} className="flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><Sparkles className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-[13px] font-semibold text-ink">{section.title}</p><p className="mt-0.5 text-xs text-ink-muted">{section.sectionType.replace("_", " ").toLowerCase()}{section.sectionType === "MANUAL" ? ` · ${section.manualProducts.length} products` : ""}</p></div>{statusBadge(section.status)}<button type="button" onClick={() => setSectionEditing(section)} className="h-8 rounded-md border border-border px-3 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint">Edit</button><button type="button" onClick={() => setDeleteSection(section)} aria-label={`Delete ${section.title}`} className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted hover:bg-danger-tint hover:text-danger-tint-ink"><Trash2 className="h-4 w-4" /></button></div>)}{!sections.length ? <p className="p-6 text-center text-[13px] text-ink-muted">No featured sections yet.</p> : null}</div></section>
  </>}
  {slideEditing ? <SlideDialog slide={slideEditing === "new" ? null : slideEditing} onClose={() => setSlideEditing(null)} onSaved={load} /> : null}
  {bannerEditing ? <BannerDialog banner={bannerEditing === "new" ? null : bannerEditing} onClose={() => setBannerEditing(null)} onSaved={load} /> : null}
  {sectionEditing ? <SectionDialog section={sectionEditing === "new" ? null : sectionEditing} onClose={() => setSectionEditing(null)} onSaved={load} /> : null}
  <Dialog open={Boolean(deleteSlide)} onOpenChange={(open) => { if (!open) setDeleteSlide(null); }}><DialogContent><DialogHeader><DialogTitle>Delete hero slide?</DialogTitle><DialogDescription>{deleteSlide ? `"${deleteSlide.headline}" will be removed from the homepage.` : ""}</DialogDescription></DialogHeader><DialogFooter><button type="button" onClick={() => setDeleteSlide(null)} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="button" onClick={() => void removeSlide()} disabled={deleting} className="inline-flex h-9 items-center gap-2 rounded-md bg-danger px-4 text-xs font-semibold text-white disabled:opacity-50">{deleting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />}Delete</button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(deleteBanner)} onOpenChange={(open) => { if (!open) setDeleteBanner(null); }}><DialogContent><DialogHeader><DialogTitle>Delete banner?</DialogTitle><DialogDescription>{deleteBanner ? `"${deleteBanner.title}" will be removed.` : ""}</DialogDescription></DialogHeader><DialogFooter><button type="button" onClick={() => setDeleteBanner(null)} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="button" onClick={() => void removeBanner()} disabled={deleting} className="inline-flex h-9 items-center gap-2 rounded-md bg-danger px-4 text-xs font-semibold text-white disabled:opacity-50">{deleting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />}Delete</button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(deleteSection)} onOpenChange={(open) => { if (!open) setDeleteSection(null); }}><DialogContent><DialogHeader><DialogTitle>Delete featured section?</DialogTitle><DialogDescription>{deleteSection ? `"${deleteSection.title}" will be removed from the storefront.` : ""}</DialogDescription></DialogHeader><DialogFooter><button type="button" onClick={() => setDeleteSection(null)} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="button" onClick={() => void removeSection()} disabled={deleting} className="inline-flex h-9 items-center gap-2 rounded-md bg-danger px-4 text-xs font-semibold text-white disabled:opacity-50">{deleting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />}Delete</button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function TrustBadgesEditor({ badges, onSaved }: { badges: TrustBadge[]; onSaved: () => Promise<void> }) {
  const [label, setLabel] = useState(""), [icon, setIcon] = useState(""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (!label.trim()) return; setSaving(true); setError(""); try { const response = await fetch("/api/hero-trust-badges", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label: label.trim(), icon: icon.trim() || undefined, sortOrder: badges.length }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Trust badge could not be added.")); setLabel(""); setIcon(""); await onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Trust badge could not be added."); } finally { setSaving(false); } }
  return <div className="mt-3 rounded-xl border border-border bg-surface p-4 shadow-card">{error ? <p className="mb-2 text-xs text-danger-tint-ink">{error}</p> : null}<div className="flex flex-wrap gap-2">{badges.map((badge) => <span key={badge.id} className="inline-flex items-center gap-1.5 rounded-full bg-neutral-tint px-3 py-1.5 text-xs font-semibold text-ink-secondary"><BadgeCheck className="h-3.5 w-3.5" />{badge.label}</span>)}{!badges.length ? <p className="text-xs text-ink-muted">No trust badges yet.</p> : null}</div><form onSubmit={(event) => void submit(event)} className="mt-3 flex flex-wrap items-end gap-2"><label className="text-[11px] font-semibold text-ink-secondary">Label<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="e.g. Free UK delivery" className="mt-1 h-8 w-56 rounded-md border border-border-strong bg-surface px-2 text-xs outline-none focus:border-accent-strong" /></label><label className="text-[11px] font-semibold text-ink-secondary">Icon name (optional)<input value={icon} onChange={(event) => setIcon(event.target.value)} placeholder="e.g. truck" className="mt-1 h-8 w-40 rounded-md border border-border-strong bg-surface px-2 text-xs outline-none focus:border-accent-strong" /></label><button type="submit" disabled={saving || !label.trim()} className="inline-flex h-8 items-center gap-1.5 rounded-md bg-ink px-3 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" /> : <Plus className="h-3.5 w-3.5" />}Add</button></form></div>;
}

function SlideDialog({ slide, onClose, onSaved }: { slide: HeroSlide | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [eyebrow, setEyebrow] = useState(slide?.eyebrow ?? ""), [headline, setHeadline] = useState(slide?.headline ?? ""), [subheading, setSubheading] = useState(slide?.subheading ?? "");
  const image = slide?.image ?? null;
  const [imageFile, setImageFile] = useState<File | null>(null), [imagePreview, setImagePreview] = useState<string | null>(null);
  const [imagePosition, setImagePosition] = useState(slide?.imagePosition ?? "center"), [tone, setTone] = useState<Tone>(slide?.tone ?? "VIOLET");
  const [ctaLabel, setCtaLabel] = useState(slide?.ctaLabel ?? ""), [ctaUrl, setCtaUrl] = useState(slide?.ctaUrl ?? "");
  const [secondaryCtaLabel, setSecondaryCtaLabel] = useState(slide?.secondaryCtaLabel ?? ""), [secondaryCtaUrl, setSecondaryCtaUrl] = useState(slide?.secondaryCtaUrl ?? "");
  const [status, setStatus] = useState<Status>(slide?.status ?? "ACTIVE"), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  function chooseImage(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; event.target.value = "";
    if (!file) return;
    if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) { setError("Hero images must be JPG, PNG or WebP files."); return; }
    if (file.size > 5 * 1024 * 1024) { setError("Hero images must be 5 MB or smaller."); return; }
    if (imagePreview) URL.revokeObjectURL(imagePreview);
    setImageFile(file); setImagePreview(URL.createObjectURL(file)); setError("");
  }

  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError("");
    try {
      let nextImage = image;
      if (imageFile) {
        const formData = new FormData();
        formData.set("file", imageFile); formData.set("ownerType", "LIBRARY"); formData.set("ownerId", "0");
        formData.set("collection", "hero-slides"); formData.set("altText", headline.trim() || "Hero slide");
        const uploadResponse = await fetch("/api/media", { method: "POST", body: formData });
        const uploadPayload = await uploadResponse.json().catch(() => ({}));
        if (!uploadResponse.ok) throw new Error(apiMessage(uploadPayload, "The image could not be uploaded."));
        nextImage = ((uploadPayload.data ?? uploadPayload) as MediaItem).url;
      }
      const body = { eyebrow: eyebrow.trim() || undefined, headline: headline.trim(), subheading: subheading.trim() || undefined, image: nextImage ?? undefined, imagePosition: imagePosition.trim() || undefined, tone, ctaLabel: ctaLabel.trim() || undefined, ctaUrl: ctaUrl.trim() || undefined, secondaryCtaLabel: secondaryCtaLabel.trim() || undefined, secondaryCtaUrl: secondaryCtaUrl.trim() || undefined, status };
      const response = await fetch(slide ? `/api/hero-slides/${slide.id}` : "/api/hero-slides", { method: slide ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Hero slide could not be saved.")); onClose(); await onSaved();
    } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Hero slide could not be saved."); } finally { setSaving(false); }
  }

  const previewSrc = imagePreview ?? (image ? (image.startsWith("/uploads/") ? mediaFileUrl(image) : image) : null);
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{slide ? "Edit hero slide" : "Add hero slide"}</DialogTitle><DialogDescription>Shown in the homepage hero carousel.</DialogDescription></DialogHeader><form onSubmit={(event) => void submit(event)}>{error ? <div role="alert" className="mb-3 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <div className="max-h-[65vh] space-y-4 overflow-y-auto pr-1">
  <div className="flex items-center gap-3"><div className="flex h-16 w-24 shrink-0 items-center justify-center overflow-hidden rounded-md border border-dashed border-border-strong bg-canvas">{previewSrc ? <NextImage unoptimized src={previewSrc} width={96} height={64} alt="" className="h-full w-full object-cover" /> : <ImageIcon className="h-5 w-5 text-ink-faint" />}</div><div><input ref={fileInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} className="hidden" /><button type="button" onClick={() => fileInputRef.current?.click()} className="inline-flex h-8 items-center gap-1.5 rounded-md border border-border-strong px-3 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint"><Upload className="h-3.5 w-3.5" />{imageFile ? "Replace selection" : image ? "Replace image" : "Choose image"}</button><p className="mt-1.5 text-[10.5px] text-ink-muted">JPG, PNG or WebP, up to 5 MB.</p></div></div>
  <label className="block text-[13px] font-semibold text-ink-secondary">Eyebrow tag<input value={eyebrow} onChange={(event) => setEyebrow(event.target.value)} placeholder="e.g. New generation graphics" className={inputClass} /></label>
  <label className="block text-[13px] font-semibold text-ink-secondary">Headline<input required value={headline} onChange={(event) => setHeadline(event.target.value)} className={inputClass} /></label>
  <label className="block text-[13px] font-semibold text-ink-secondary">Description<textarea value={subheading} onChange={(event) => setSubheading(event.target.value)} rows={2} className={`${inputClass} h-auto resize-y py-2`} /></label>
  <div className="grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Image focal point<input value={imagePosition} onChange={(event) => setImagePosition(event.target.value)} placeholder="e.g. 68% center" className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">Colour tone<select value={tone} onChange={(event) => setTone(event.target.value as Tone)} className={inputClass}>{toneOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div>
  <div className="grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Primary CTA label<input value={ctaLabel} onChange={(event) => setCtaLabel(event.target.value)} className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">Primary CTA URL<input value={ctaUrl} onChange={(event) => setCtaUrl(event.target.value)} className={inputClass} /></label></div>
  <div className="grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Secondary CTA label<input value={secondaryCtaLabel} onChange={(event) => setSecondaryCtaLabel(event.target.value)} className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">Secondary CTA URL<input value={secondaryCtaUrl} onChange={(event) => setSecondaryCtaUrl(event.target.value)} className={inputClass} /></label></div>
  <label className="block text-[13px] font-semibold text-ink-secondary">Status<select value={status} onChange={(event) => setStatus(event.target.value as Status)} className={inputClass}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label>
  </div>
  <DialogFooter className="mt-4"><button type="button" onClick={onClose} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="submit" disabled={saving} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Save</button></DialogFooter></form></DialogContent></Dialog>;
}

function BannerDialog({ banner, onClose, onSaved }: { banner: Banner | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [title, setTitle] = useState(banner?.title ?? ""), [slug, setSlug] = useState(banner?.slug ?? "");
  const [linkType, setLinkType] = useState<LinkType>(banner?.linkType ?? "CUSTOM_URL");
  const [target, setTarget] = useState(banner ? String(banner.productId ?? banner.categoryId ?? banner.brandId ?? banner.customUrl ?? "") : "");
  const [position, setPosition] = useState(banner?.position ?? ""), [displayOrder, setDisplayOrder] = useState(banner?.displayOrder != null ? String(banner.displayOrder) : "0");
  const [status, setStatus] = useState<Status>(banner?.status ?? "ACTIVE"), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError("");
    const body: Record<string, unknown> = { title: title.trim(), slug: slug.trim(), linkType, position: position.trim(), displayOrder: Number(displayOrder), status };
    if (linkType === "PRODUCT") body.productId = Number(target); else if (linkType === "CATEGORY") body.categoryId = Number(target); else if (linkType === "BRAND") body.brandId = Number(target); else body.customUrl = target.trim();
    try { const response = await fetch(banner ? `/api/banners/${banner.id}` : "/api/banners", { method: banner ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Banner could not be saved.")); onClose(); await onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Banner could not be saved."); } finally { setSaving(false); }
  }
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>{banner ? "Edit banner" : "Add banner"}</DialogTitle><DialogDescription>Promotional banner shown in a storefront position.</DialogDescription></DialogHeader><form onSubmit={(event) => void submit(event)}>{error ? <div role="alert" className="mb-3 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}<div className="grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">Slug<input required value={slug} onChange={(event) => setSlug(event.target.value)} className={`${inputClass} font-mono`} /></label></div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Link type<select value={linkType} onChange={(event) => setLinkType(event.target.value as LinkType)} className={inputClass}><option value="PRODUCT">Product</option><option value="CATEGORY">Category</option><option value="BRAND">Brand</option><option value="CUSTOM_URL">Custom URL</option></select></label><label className="text-[13px] font-semibold text-ink-secondary">{linkType === "CUSTOM_URL" ? "URL" : `${linkType.charAt(0)}${linkType.slice(1).toLowerCase()} ID`}<input required value={target} onChange={(event) => setTarget(event.target.value)} className={inputClass} /></label></div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Position<input required value={position} onChange={(event) => setPosition(event.target.value)} placeholder="e.g. homepage-mid" className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">Display order<input type="number" value={displayOrder} onChange={(event) => setDisplayOrder(event.target.value)} className={inputClass} /></label></div><label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Status<select value={status} onChange={(event) => setStatus(event.target.value as Status)} className={inputClass}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><DialogFooter className="mt-4"><button type="button" onClick={onClose} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="submit" disabled={saving} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Save</button></DialogFooter></form></DialogContent></Dialog>;
}

function SectionDialog({ section, onClose, onSaved }: { section: FeaturedSection | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [title, setTitle] = useState(section?.title ?? ""), [slug, setSlug] = useState(section?.slug ?? "");
  const [sectionType, setSectionType] = useState<SectionType>(section?.sectionType ?? "FEATURED");
  const [manualIds, setManualIds] = useState(section?.manualProducts.map((product) => product.productId).join(", ") ?? "");
  const [status, setStatus] = useState<Status>(section?.status ?? "ACTIVE"), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError("");
    const body: Record<string, unknown> = { title: title.trim(), slug: slug.trim(), sectionType, status };
    if (sectionType === "MANUAL") body.manualProductIds = manualIds.split(",").map((value) => value.trim()).filter(Boolean).map(Number);
    try { const response = await fetch(section ? `/api/featured-sections/${section.id}` : "/api/featured-sections", { method: section ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Featured section could not be saved.")); onClose(); await onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Featured section could not be saved."); } finally { setSaving(false); }
  }
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>{section ? "Edit featured section" : "Add featured section"}</DialogTitle><DialogDescription>A product rail shown on the storefront.</DialogDescription></DialogHeader><form onSubmit={(event) => void submit(event)}>{error ? <div role="alert" className="mb-3 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}<div className="grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">Slug<input required value={slug} onChange={(event) => setSlug(event.target.value)} className={`${inputClass} font-mono`} /></label></div><label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Section type<select value={sectionType} onChange={(event) => setSectionType(event.target.value as SectionType)} className={inputClass}><option value="NEWLY_ADDED">Newly added</option><option value="FEATURED">Featured</option><option value="BEST_SELLER">Best seller</option><option value="TOP_RATED">Top rated</option><option value="MANUAL">Manual selection</option></select></label>{sectionType === "MANUAL" ? <label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Product IDs (comma-separated)<input value={manualIds} onChange={(event) => setManualIds(event.target.value)} placeholder="e.g. 12, 45, 78" className={inputClass} /></label> : null}<label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Status<select value={status} onChange={(event) => setStatus(event.target.value as Status)} className={inputClass}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><DialogFooter className="mt-4"><button type="button" onClick={onClose} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="submit" disabled={saving} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Save</button></DialogFooter></form></DialogContent></Dialog>;
}
