"use client";

import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, CircleHelp, ImageIcon, LoaderCircle, Plus, Save, Upload } from "lucide-react";
import { toast } from "sonner";
import { RichTextEditor } from "@/components/ui/rich-text-editor";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { collectionFromApi } from "@/lib/api-response";
import { mediaFileUrl } from "@/lib/media";

type CategoryOption = { id: number; title: string; slug: string };
type RedirectBehaviour = "NOT_FOUND" | "GONE" | "REDIRECT_CATEGORY_301" | "REDIRECT_CATEGORY_302";
type TwitterCard = "SUMMARY" | "SUMMARY_LARGE_IMAGE";
type SchemaType = "AUTOMATIC" | "CUSTOM";
type CategoryFaq = { question: string; answer: string };
const inputClass = "mt-2 h-10 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
const labelClass = "text-[13px] font-semibold text-ink-secondary";
function message(payload: unknown, fallback: string) { if (payload && typeof payload === "object") { const record = payload as { message?: unknown; error?: { message?: unknown } }; const value = record.message ?? record.error?.message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function Help({ label, children }: { label: string; children: string }) { return <Tooltip><TooltipTrigger render={<button type="button" aria-label={`Help for ${label}`} className="inline-flex h-5 w-5 items-center justify-center rounded-md text-ink-muted hover:bg-neutral-tint hover:text-ink" />}><CircleHelp className="h-3.5 w-3.5" /></TooltipTrigger><TooltipContent side="top" align="start" className="max-w-72 bg-ink px-3 py-2 text-[11px] leading-4 text-white">{children}</TooltipContent></Tooltip>; }
function parseFaqSchema(text: string): CategoryFaq[] | null { try { const parsed = JSON.parse(text); const entities = Array.isArray(parsed.mainEntity) ? parsed.mainEntity : []; return entities.map((entity: { name?: string; acceptedAnswer?: { text?: string } }) => ({ question: entity.name ?? "", answer: entity.acceptedAnswer?.text ?? "" })); } catch { return null; } }

export function CategoryFormPage({ categoryId }: { categoryId?: number }) {
  const router = useRouter(), editing = Number.isInteger(categoryId);
  const [categories, setCategories] = useState<CategoryOption[]>([]), [loading, setLoading] = useState(Boolean(editing));
  const [title, setTitle] = useState(""), [slug, setSlug] = useState(""), [description, setDescription] = useState(""), [additionalDescription, setAdditionalDescription] = useState("");
  const [parentId, setParentId] = useState(""), [sortOrder, setSortOrder] = useState("0"), [status, setStatus] = useState<"ACTIVE" | "INACTIVE">("ACTIVE"), [isIndexable, setIsIndexable] = useState(true), [showOnHomepage, setShowOnHomepage] = useState(true);
  const [pageHeader, setPageHeader] = useState(""), [metaTitle, setMetaTitle] = useState(""), [metaKeywords, setMetaKeywords] = useState(""), [metaDescription, setMetaDescription] = useState("");
  const [redirectBehaviour, setRedirectBehaviour] = useState<RedirectBehaviour>("NOT_FOUND"), [redirectTargetId, setRedirectTargetId] = useState("");
  const [ogTitle, setOgTitle] = useState(""), [ogImage, setOgImage] = useState(""), [ogImageFile, setOgImageFile] = useState<File | null>(null), [ogImageAlt, setOgImageAlt] = useState(""), [ogDescription, setOgDescription] = useState("");
  const [twitterTitle, setTwitterTitle] = useState(""), [twitterCard, setTwitterCard] = useState<TwitterCard>("SUMMARY_LARGE_IMAGE"), [twitterImage, setTwitterImage] = useState(""), [twitterImageFile, setTwitterImageFile] = useState<File | null>(null), [twitterDescription, setTwitterDescription] = useState("");
  const [schemaType, setSchemaType] = useState<SchemaType>("AUTOMATIC"), [customSchema, setCustomSchema] = useState("");
  const [faqs, setFaqs] = useState<CategoryFaq[]>([]), [faqSchema, setFaqSchema] = useState(""), [faqSchemaError, setFaqSchemaError] = useState("");
  const [coverImage, setCoverImage] = useState(""), [coverImageFile, setCoverImageFile] = useState<File | null>(null), [coverImageAlt, setCoverImageAlt] = useState("");
  const [thumbnailImage, setThumbnailImage] = useState(""), [thumbnailImageFile, setThumbnailImageFile] = useState<File | null>(null), [thumbnailImageAlt, setThumbnailImageAlt] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => { const timer = window.setTimeout(async () => { try { const categoryResponse = await fetch("/api/catalog/categories?page=1&perPage=100"); const categoryPayload = await categoryResponse.json(); setCategories(collectionFromApi<CategoryOption>(categoryPayload).filter((item) => item.id !== categoryId)); if (editing) { const response = await fetch(`/api/catalog/categories/${categoryId}`); const payload = await response.json(); if (!response.ok) throw new Error(message(payload, "Category could not be loaded.")); const item = payload.data ?? payload; setTitle(item.title); setSlug(item.slug); setDescription(item.description ?? ""); setAdditionalDescription(item.additionalDescription ?? ""); setParentId(item.parentId ? String(item.parentId) : ""); setSortOrder(String(item.sortOrder)); setStatus(item.status); setIsIndexable(item.isIndexable); setShowOnHomepage(item.showOnHomepage); setCoverImage(item.coverImage ?? ""); setCoverImageAlt(item.coverImageAlt ?? ""); setThumbnailImage(item.thumbnailImage ?? ""); setThumbnailImageAlt(item.thumbnailImageAlt ?? ""); setPageHeader(item.pageHeader ?? ""); setMetaTitle(item.metaTitle ?? ""); setMetaKeywords(item.metaKeywords ?? ""); setMetaDescription(item.metaDescription ?? ""); setOgTitle(item.ogTitle ?? ""); setOgImage(item.ogImage ?? ""); setOgImageAlt(item.ogImageAlt ?? ""); setOgDescription(item.ogDescription ?? ""); setTwitterTitle(item.twitterTitle ?? ""); setTwitterCard(item.twitterCard ?? "SUMMARY_LARGE_IMAGE"); setTwitterImage(item.twitterImage ?? ""); setTwitterDescription(item.twitterDescription ?? ""); setSchemaType(item.schemaType ?? "AUTOMATIC"); setCustomSchema(item.customSchema ?? ""); setFaqs((item.faqs ?? []).map((faq: CategoryFaq) => ({ question: faq.question, answer: faq.answer }))); setFaqSchema(item.faqSchema ?? ""); setRedirectBehaviour(item.offlineRedirectBehavior ?? "NOT_FOUND"); setRedirectTargetId(item.redirectTargetCategoryId ? String(item.redirectTargetCategoryId) : ""); } } catch (loadError) { toast.error(loadError instanceof Error ? loadError.message : "Category could not be loaded."); } finally { setLoading(false); } }, 0); return () => window.clearTimeout(timer); }, [categoryId, editing]);
  function updateTitle(value: string) { const generated = slugify(title); setTitle(value); if (!slug || slug === generated) setSlug(slugify(value)); }
  async function uploadToLibrary(file: File, collection: string, altText: string) { const body = new FormData(); body.set("file", file); body.set("ownerType", "LIBRARY"); body.set("ownerId", "0"); body.set("collection", collection); body.set("altText", altText || title || collection); const response = await fetch("/api/media", { method: "POST", body }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(message(payload, `${file.name} could not be uploaded.`)); return (payload.data ?? payload).url as string; }

  function addFaq() { setFaqs((current) => [...current, { question: "", answer: "" }]); }
  function updateFaq(index: number, field: keyof CategoryFaq, value: string) { setFaqs((current) => current.map((faq, i) => (i === index ? { ...faq, [field]: value } : faq))); }
  function removeFaq(index: number) { setFaqs((current) => current.filter((_, i) => i !== index)); }
  function autoFillFaqsFromSchema() { const parsed = parseFaqSchema(faqSchema); if (!parsed) { setFaqSchemaError("Could not parse this JSON-LD."); return; } setFaqSchemaError(""); setFaqs(parsed); }

  async function submit(event: FormEvent) {
    event.preventDefault(); if (!title.trim() || !slug.trim()) { toast.error("Category name and friendly URL are required."); return; } setSaving(true);
    try {
      const nextCoverImageAlt = coverImageAlt.trim() || title.trim();
      const nextThumbnailImageAlt = thumbnailImageAlt.trim() || title.trim();
      const nextCoverImage = coverImageFile ? await uploadToLibrary(coverImageFile, "category-cover", nextCoverImageAlt) : coverImage || undefined;
      const nextThumbnailImage = thumbnailImageFile ? await uploadToLibrary(thumbnailImageFile, "category-thumbnail", nextThumbnailImageAlt) : thumbnailImage || undefined;
      const nextOgImage = ogImageFile ? await uploadToLibrary(ogImageFile, "category-og-image", ogImageAlt) : ogImage || undefined;
      const nextTwitterImage = twitterImageFile ? await uploadToLibrary(twitterImageFile, "category-twitter-image", twitterTitle) : twitterImage || undefined;
      const response = await fetch(editing ? `/api/catalog/categories/${categoryId}` : "/api/catalog/categories", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), slug: slug.trim(), description: description || undefined, additionalDescription: additionalDescription || undefined, parentId: parentId ? Number(parentId) : null, sortOrder: Number(sortOrder || 0), status, isIndexable, showOnHomepage, coverImage: nextCoverImage, coverImageAlt: nextCoverImage ? nextCoverImageAlt : undefined, thumbnailImage: nextThumbnailImage, thumbnailImageAlt: nextThumbnailImage ? nextThumbnailImageAlt : undefined, pageHeader: pageHeader.trim() || undefined, metaTitle: metaTitle.trim() || undefined, metaKeywords: metaKeywords.trim() || undefined, metaDescription: metaDescription.trim() || undefined, ogTitle: ogTitle.trim() || undefined, ogImage: nextOgImage, ogImageAlt: ogImageAlt.trim() || undefined, ogDescription: ogDescription.trim() || undefined, twitterTitle: twitterTitle.trim() || undefined, twitterCard, twitterImage: nextTwitterImage, twitterDescription: twitterDescription.trim() || undefined, schemaType, customSchema: schemaType === "CUSTOM" ? customSchema.trim() || undefined : undefined, faqSchema: faqSchema.trim() || undefined, faqs: faqs.filter((faq) => faq.question.trim() && faq.answer.trim()).map((faq) => ({ question: faq.question.trim(), answer: faq.answer.trim() })), offlineRedirectBehavior: redirectBehaviour, redirectTargetCategoryId: redirectBehaviour.startsWith("REDIRECT_CATEGORY") && redirectTargetId ? Number(redirectTargetId) : undefined }) });
      const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(message(payload, "Category could not be saved."));
      toast.success(editing ? "Category updated." : "Category created.");
      router.push("/categories"); router.refresh();
    } catch (saveError) { toast.error(saveError instanceof Error ? saveError.message : "Category could not be saved."); } finally { setSaving(false); }
  }

  const plainDescription = description.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim(), previewTitle = metaTitle.trim() || title || "Category title", previewDescription = metaDescription.trim() || plainDescription || "Add a category description to preview its search result.";
  if (loading) return <div className="flex min-h-80 items-center justify-center"><LoaderCircle className="h-6 w-6 animate-spin text-ink-muted" /></div>;
  return <form onSubmit={(event) => void submit(event)} className="w-full pb-20"><div><nav className="flex items-center gap-1.5 text-xs text-ink-muted"><Link href="/categories" className="hover:text-ink">Categories</Link><ChevronRight className="h-3.5 w-3.5" /><span>{editing ? "Edit category" : "Add category"}</span></nav><h1 className="mt-2 text-[22px] font-semibold text-ink">{editing ? `Edit ${title}` : "Add category"}</h1><p className="mt-1 text-[13.5px] text-ink-muted">Create one English catalogue category. No localisation fields are included.</p></div>
  <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-2">
  <section className="space-y-7 rounded-xl border border-border bg-surface p-5 shadow-card"><div className="grid gap-4 md:grid-cols-[1fr_220px]"><label className={labelClass}>Category name<input autoFocus={!editing} value={title} onChange={(event) => updateTitle(event.target.value)} maxLength={255} placeholder="e.g. Graphics Cards" className={inputClass} /></label><label className={labelClass}>Status<select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className={inputClass}><option value="ACTIVE">Displayed</option><option value="INACTIVE">Disabled</option></select></label></div>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Category content</h2><div className="mt-4 space-y-5"><div className={labelClass}><span className="inline-flex items-center gap-1">Description<Help label="Description">Introduce the category and help customers understand which products it contains.</Help></span><RichTextEditor value={description} onChange={setDescription} ariaLabel="Category description" placeholder="Describe this category and the products customers will find here." minHeight="sm" /></div></div></section>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Images</h2><p className="mt-1 text-xs text-ink-muted">Upload a wide category cover and a compact thumbnail for menus or subcategory cards.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="space-y-3"><FilePicker label="Category cover" hint="Recommended: wide landscape image. JPG, PNG, WebP or AVIF, up to 1MB." file={coverImageFile} setFile={setCoverImageFile} existingUrl={coverImage} /><label className={labelClass}>Category cover ALT text<input value={coverImageAlt} onChange={(event) => setCoverImageAlt(event.target.value)} placeholder={title || "Category name"} className={inputClass} /></label></div><div className="space-y-3"><FilePicker label="Category thumbnail" hint="Recommended: 380×280px. JPG, PNG, WebP or AVIF, up to 1MB." file={thumbnailImageFile} setFile={setThumbnailImageFile} existingUrl={thumbnailImage} /><label className={labelClass}>Category thumbnail ALT text<input value={thumbnailImageAlt} onChange={(event) => setThumbnailImageAlt(event.target.value)} placeholder={title || "Category name"} className={inputClass} /></label></div></div></section>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Hierarchy and offline behaviour</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className={labelClass}>Parent category<select value={parentId} onChange={(event) => setParentId(event.target.value)} className={inputClass}><option value="">Top level</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.title}</option>)}</select></label><label className={labelClass}>Position<input type="number" min="0" value={sortOrder} onChange={(event) => setSortOrder(event.target.value)} className={inputClass} /></label><label className="flex items-center gap-3 rounded-md border border-border p-3 text-[13px] font-semibold text-ink-secondary md:col-span-2"><input type="checkbox" checked={showOnHomepage} onChange={(event) => setShowOnHomepage(event.target.checked)} className="h-4 w-4 accent-ink" />Show on homepage<span className="font-normal text-ink-muted">— include this category in the &ldquo;Shop by category&rdquo; homepage section.</span></label><label className={labelClass}>When category is disabled<select value={redirectBehaviour} onChange={(event) => setRedirectBehaviour(event.target.value as RedirectBehaviour)} className={inputClass}><option value="NOT_FOUND">Not found (404)</option><option value="GONE">Permanently removed (410)</option><option value="REDIRECT_CATEGORY_301">Permanent category redirect (301)</option><option value="REDIRECT_CATEGORY_302">Temporary category redirect (302)</option></select></label>{redirectBehaviour.startsWith("REDIRECT_CATEGORY") ? <label className={labelClass}>Redirect target<select value={redirectTargetId} onChange={(event) => setRedirectTargetId(event.target.value)} className={inputClass}><option value="">Use parent category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.title}</option>)}</select></label> : null}</div></section>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">FAQs</h2><p className="mt-1 text-xs text-ink-muted">Shown as an accordion on the category page and used to auto-generate FAQ structured data (FAQPage schema) for search engines.</p>
    {faqs.length ? <div className="mt-3 space-y-3">{faqs.map((faq, index) => <div key={index} className="rounded-md border border-border p-3"><div className="flex items-center justify-between"><span className="text-[13px] font-semibold text-ink">FAQ</span><button type="button" onClick={() => removeFaq(index)} className="inline-flex h-7 items-center gap-1 rounded-md border border-danger px-2 text-[11px] font-semibold text-danger hover:bg-danger-tint">Remove</button></div><label className="mt-3 block text-[13px] font-semibold text-ink-secondary">Question<textarea value={faq.question} onChange={(event) => updateFaq(index, "question", event.target.value)} rows={2} placeholder="e.g. Are these jars food-grade?" className={`${inputClass} h-auto resize-y py-3`} /></label><label className="mt-3 block text-[13px] font-semibold text-ink-secondary">Answer<textarea value={faq.answer} onChange={(event) => updateFaq(index, "answer", event.target.value)} rows={2} placeholder="e.g. Yes, all Pethiyan jars are BPA-free…" className={`${inputClass} h-auto resize-y py-3`} /></label></div>)}</div> : null}
    <button type="button" onClick={addFaq} className="mt-3 inline-flex h-9 w-fit items-center gap-1.5 rounded-md border border-border-strong px-3 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint"><Plus className="h-3.5 w-3.5" />Add FAQ</button>
    <details className="mt-4"><summary className="cursor-pointer text-xs font-semibold text-ink-secondary">Advanced: override generated schema</summary><div className="mt-3"><label className={labelClass}>FAQ Schema JSON-LD<textarea value={faqSchema} onChange={(event) => setFaqSchema(event.target.value)} rows={4} placeholder='{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[...]}' className={`${inputClass} h-auto resize-y py-3 font-mono text-xs`} /></label>{faqSchemaError ? <p className="mt-1 text-xs text-danger-tint-ink">{faqSchemaError}</p> : null}<p className="mt-2 text-xs text-ink-muted">Optional. If set, replaces the auto-generated FAQ schema entirely (the visible FAQ list above is unaffected). Leave blank to auto-generate from the Q&amp;A pairs above.</p><button type="button" onClick={autoFillFaqsFromSchema} disabled={!faqSchema.trim()} className="mt-3 inline-flex h-9 items-center gap-1.5 rounded-md border border-border-strong px-3 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint disabled:opacity-50">Auto-fill Q&amp;A from Schema</button></div></details>
  </section>
  </section>

  <section className="space-y-5 rounded-xl border border-border bg-surface p-5 shadow-card"><h2 className="text-sm font-semibold text-ink">Search engine optimisation</h2><div className="rounded-lg border border-border p-4 shadow-card"><p className="truncate text-xs text-[#202124]">ukcomputershop.co.uk › category › {slug || "category-url"}</p><p className="mt-1 truncate text-lg text-[#1a0dab]">{previewTitle}</p><p className="mt-1 line-clamp-2 text-[13px] leading-5 text-[#4d5156]">{previewDescription}</p></div>
  <div className="mt-4 space-y-5">
    <div className={labelClass}><span className="inline-flex items-center gap-1">On-page SEO content<Help label="On-page SEO content">Optional longer content shown after the product listing, useful for buying guidance and category SEO.</Help></span><RichTextEditor value={additionalDescription} onChange={setAdditionalDescription} ariaLabel="On-page SEO content" placeholder="Add buying guidance, compatibility information or longer SEO content." minHeight="sm" /></div>
    <label className={labelClass}>Page header (H1)<input value={pageHeader} onChange={(event) => setPageHeader(event.target.value)} placeholder={title || "Category title"} className={inputClass} /></label>
    <label className="flex items-center gap-3 rounded-md border border-border p-3 text-[13px] font-semibold text-ink-secondary"><input type="checkbox" checked={isIndexable} onChange={(event) => setIsIndexable(event.target.checked)} className="h-4 w-4 accent-ink" />Allow search engines to index this category<span className="font-normal text-ink-muted">— uncheck to add noindex (e.g. draft, unlisted, or duplicate category).</span></label>
    <label className={labelClass}>Meta title<div className="relative"><input value={metaTitle} onChange={(event) => setMetaTitle(event.target.value)} maxLength={70} placeholder={title || "Category title"} className={`${inputClass} pr-14`} /><span className="absolute bottom-3 right-3 text-[10.5px] text-ink-muted">{metaTitle.length}/70</span></div></label>
    <label className={labelClass}>Meta keywords<input value={metaKeywords} onChange={(event) => setMetaKeywords(event.target.value)} placeholder="e.g. graphics cards, gpu, gaming pc parts" className={inputClass} /></label>
    <label className={labelClass}>Meta description<div className="relative"><textarea value={metaDescription} onChange={(event) => setMetaDescription(event.target.value)} maxLength={320} rows={3} className={`${inputClass} h-auto py-3 pb-7`} /><span className="absolute bottom-2.5 right-3 text-[10.5px] text-ink-muted">{metaDescription.length}/320</span></div></label>
    <label className={labelClass}>Friendly URL<div className="mt-2 flex h-10 items-center rounded-md border border-border-strong"><span className="hidden border-r border-border px-3 text-xs text-ink-muted sm:block">/category/</span><input value={slug} onChange={(event) => setSlug(slugify(event.target.value))} className="min-w-0 flex-1 px-3 font-mono text-xs outline-none" /></div></label>
  </div>

  <div className="mt-6 border-t border-border pt-5"><h3 className="text-[13px] font-semibold text-ink">Open Graph (Facebook, LinkedIn)</h3><div className="mt-3 grid gap-4"><label className={labelClass}>OG title<input value={ogTitle} onChange={(event) => setOgTitle(event.target.value)} placeholder={metaTitle || title} className={inputClass} /></label><div className="grid gap-4 md:grid-cols-2"><FilePicker label="OG image" hint="Recommended: 1200×630px." file={ogImageFile} setFile={setOgImageFile} existingUrl={ogImage} /><label className={labelClass}>OG image ALT text<input value={ogImageAlt} onChange={(event) => setOgImageAlt(event.target.value)} className={inputClass} /></label></div><label className={labelClass}>OG description<textarea value={ogDescription} onChange={(event) => setOgDescription(event.target.value)} rows={2} className={`${inputClass} h-auto py-3`} /></label></div></div>

  <div className="mt-6 border-t border-border pt-5"><h3 className="text-[13px] font-semibold text-ink">Twitter / X card</h3><div className="mt-3 grid gap-4"><div className="grid gap-4 md:grid-cols-2"><label className={labelClass}>Twitter title<input value={twitterTitle} onChange={(event) => setTwitterTitle(event.target.value)} placeholder={metaTitle || title} className={inputClass} /></label><label className={labelClass}>Twitter card type<select value={twitterCard} onChange={(event) => setTwitterCard(event.target.value as TwitterCard)} className={inputClass}><option value="SUMMARY">Summary</option><option value="SUMMARY_LARGE_IMAGE">Summary with large image</option></select></label></div><FilePicker label="Twitter image" hint="Recommended: 1200×675px." file={twitterImageFile} setFile={setTwitterImageFile} existingUrl={twitterImage} /><label className={labelClass}>Twitter description<textarea value={twitterDescription} onChange={(event) => setTwitterDescription(event.target.value)} rows={2} className={`${inputClass} h-auto py-3`} /></label></div></div>

  <div className="mt-6 border-t border-border pt-5"><h3 className="text-[13px] font-semibold text-ink">Page schema</h3><div className="mt-3 grid gap-4"><label className={labelClass}>Schema source<select value={schemaType} onChange={(event) => setSchemaType(event.target.value as SchemaType)} className={inputClass}><option value="AUTOMATIC">Automatic</option><option value="CUSTOM">Custom</option></select></label>{schemaType === "CUSTOM" ? <label className={labelClass}>Custom JSON-LD<textarea value={customSchema} onChange={(event) => setCustomSchema(event.target.value)} rows={6} placeholder={'{\n  "@context": "https://schema.org",\n  "@type": "CollectionPage"\n}'} className={`${inputClass} h-auto resize-y py-3 font-mono text-xs`} /></label> : null}</div></div>
  </section>
  </div>
  <div className="fixed bottom-0 left-0 right-0 z-20 border-t border-border bg-surface/95 px-4 py-3 backdrop-blur lg:left-64"><div className="flex items-center justify-between"><Link href="/categories" className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-3.5 text-[13px] font-semibold text-ink-secondary"><ArrowLeft className="h-4 w-4" />Back to categories</Link><button type="submit" disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : editing ? <Save className="h-4 w-4" /> : <Check className="h-4 w-4" />}{editing ? "Save changes" : "Create category"}</button></div></div></form>;
}

function FilePicker({ label, hint, file, setFile, existingUrl }: { label: string; hint: string; file: File | null; setFile: (file: File | null) => void; existingUrl?: string }) {
  const previewUrl = useMemo(() => (file ? URL.createObjectURL(file) : null), [file]);
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); }, [previewUrl]);
  const src = previewUrl ?? (existingUrl ? mediaFileUrl(existingUrl) : null);
  return <label className="block rounded-lg border border-dashed border-border-strong bg-canvas p-4"><span className="flex items-center gap-2 text-[13px] font-semibold text-ink"><ImageIcon className="h-4 w-4 text-ink-muted" />{label}</span><span className="mt-1 block text-xs text-ink-muted">{hint}</span>{src ? <div className="relative mt-3 h-28 w-full overflow-hidden rounded-md border border-border bg-neutral-tint"><Image src={src} alt="" fill unoptimized sizes="400px" className="object-cover" /></div> : null}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="sr-only" /><span className="mt-4 inline-flex h-9 items-center gap-2 rounded-md border border-border bg-surface px-3 text-xs font-semibold text-ink-secondary"><Upload className="h-4 w-4" />{file ? "Change image" : existingUrl ? "Replace image" : "Choose image"}</span>{file ? <span className="mt-2 block truncate text-xs font-medium text-ink">{file.name}</span> : existingUrl ? <span className="mt-2 block truncate text-xs font-medium text-ink">{existingUrl.split("/").pop()}</span> : null}</label>;
}
