"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Check, ChevronRight, CircleHelp, ImageIcon, LoaderCircle, Save, Upload } from "lucide-react";
import { RichTextEditor } from "@/components/ui/rich-text-editor";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { collectionFromApi } from "@/lib/api-response";

type CategoryOption = { id: number; title: string; slug: string };
type RedirectBehaviour = "NOT_FOUND" | "GONE" | "REDIRECT_CATEGORY_301" | "REDIRECT_CATEGORY_302";
const inputClass = "mt-2 h-10 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
const labelClass = "text-[13px] font-semibold text-ink-secondary";
function message(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function Help({ label, children }: { label: string; children: string }) { return <Tooltip><TooltipTrigger render={<button type="button" aria-label={`Help for ${label}`} className="inline-flex h-5 w-5 items-center justify-center rounded-md text-ink-muted hover:bg-neutral-tint hover:text-ink" />}><CircleHelp className="h-3.5 w-3.5" /></TooltipTrigger><TooltipContent side="top" align="start" className="max-w-72 bg-ink px-3 py-2 text-[11px] leading-4 text-white">{children}</TooltipContent></Tooltip>; }

export function CategoryFormPage({ categoryId }: { categoryId?: number }) {
  const router = useRouter(), editing = Number.isInteger(categoryId);
  const [categories, setCategories] = useState<CategoryOption[]>([]), [loading, setLoading] = useState(Boolean(editing));
  const [title, setTitle] = useState(""), [slug, setSlug] = useState(""), [description, setDescription] = useState(""), [additionalDescription, setAdditionalDescription] = useState("");
  const [parentId, setParentId] = useState(""), [sortOrder, setSortOrder] = useState("0"), [status, setStatus] = useState<"ACTIVE" | "INACTIVE">("ACTIVE"), [isIndexable, setIsIndexable] = useState(true);
  const [metaTitle, setMetaTitle] = useState(""), [metaDescription, setMetaDescription] = useState(""), [redirectBehaviour, setRedirectBehaviour] = useState<RedirectBehaviour>("NOT_FOUND"), [redirectTargetId, setRedirectTargetId] = useState("");
  const [cover, setCover] = useState<File | null>(null), [thumbnail, setThumbnail] = useState<File | null>(null), [saving, setSaving] = useState(false), [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(async () => { try { const categoryResponse = await fetch("/api/catalog/categories?page=1&perPage=100"); const categoryPayload = await categoryResponse.json(); setCategories(collectionFromApi<CategoryOption>(categoryPayload).filter((item) => item.id !== categoryId)); if (editing) { const response = await fetch(`/api/catalog/categories/${categoryId}`); const payload = await response.json(); if (!response.ok) throw new Error(message(payload, "Category could not be loaded.")); const item = payload.data ?? payload; setTitle(item.title); setSlug(item.slug); setDescription(item.description ?? ""); setAdditionalDescription(item.additionalDescription ?? ""); setParentId(item.parentId ? String(item.parentId) : ""); setSortOrder(String(item.sortOrder)); setStatus(item.status); setIsIndexable(item.isIndexable); setMetaTitle(item.metaTitle ?? ""); setMetaDescription(item.metaDescription ?? ""); setRedirectBehaviour(item.offlineRedirectBehavior ?? "NOT_FOUND"); setRedirectTargetId(item.redirectTargetCategoryId ? String(item.redirectTargetCategoryId) : ""); } } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Category could not be loaded."); } finally { setLoading(false); } }, 0); return () => window.clearTimeout(timer); }, [categoryId, editing]);
  function updateTitle(value: string) { const generated = slugify(title); setTitle(value); if (!slug || slug === generated) setSlug(slugify(value)); }
  async function uploadFile(file: File, ownerType: string, ownerId: number) { const body = new FormData(); body.set("file", file); body.set("ownerType", ownerType); body.set("ownerId", String(ownerId)); body.set("collection", "categories"); const response = await fetch("/api/media", { method: "POST", body }); if (!response.ok) throw new Error(`Category saved, but ${file.name} could not be uploaded.`); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || !slug.trim()) { setError("Category name and friendly URL are required."); return; } setSaving(true); setError(""); try { const response = await fetch(editing ? `/api/catalog/categories/${categoryId}` : "/api/catalog/categories", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), slug: slug.trim(), description: description || undefined, additionalDescription: additionalDescription || undefined, parentId: parentId ? Number(parentId) : null, sortOrder: Number(sortOrder || 0), status, isIndexable, metaTitle: metaTitle.trim() || undefined, metaDescription: metaDescription.trim() || undefined, offlineRedirectBehavior: redirectBehaviour, redirectTargetCategoryId: redirectBehaviour.startsWith("REDIRECT_CATEGORY") && redirectTargetId ? Number(redirectTargetId) : undefined }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(message(payload, "Category could not be saved.")); const saved = payload.data ?? payload; const id = Number(categoryId ?? saved.id); if (cover) await uploadFile(cover, "CATEGORY_COVER", id); if (thumbnail) await uploadFile(thumbnail, "CATEGORY_THUMBNAIL", id); router.push("/categories"); router.refresh(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Category could not be saved."); } finally { setSaving(false); } }
  const plainDescription = description.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim(), previewTitle = metaTitle.trim() || title || "Category title", previewDescription = metaDescription.trim() || plainDescription || "Add a category description to preview its search result.";
  if (loading) return <div className="flex min-h-80 items-center justify-center"><LoaderCircle className="h-6 w-6 animate-spin text-ink-muted" /></div>;
  return <form onSubmit={(event) => void submit(event)} className="w-full pb-20"><div><nav className="flex items-center gap-1.5 text-xs text-ink-muted"><Link href="/categories" className="hover:text-ink">Categories</Link><ChevronRight className="h-3.5 w-3.5" /><span>{editing ? "Edit category" : "Add category"}</span></nav><h1 className="mt-2 text-[22px] font-semibold text-ink">{editing ? `Edit ${title}` : "Add category"}</h1><p className="mt-1 text-[13.5px] text-ink-muted">Create one English catalogue category. No localisation fields are included.</p></div>
  {error ? <div role="alert" className="mt-4 flex gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <section className="mt-4 space-y-7 rounded-xl border border-border bg-surface p-5 shadow-card"><div className="grid gap-4 md:grid-cols-[1fr_220px]"><label className={labelClass}>Category name<input autoFocus={!editing} value={title} onChange={(event) => updateTitle(event.target.value)} maxLength={255} placeholder="e.g. Graphics Cards" className={inputClass} /></label><label className={labelClass}>Status<select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className={inputClass}><option value="ACTIVE">Displayed</option><option value="INACTIVE">Disabled</option></select></label></div>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Category content</h2><div className="mt-4 space-y-5"><div className={labelClass}><span className="inline-flex items-center gap-1">Description<Help label="Description">Introduce the category and help customers understand which products it contains.</Help></span><RichTextEditor value={description} onChange={setDescription} ariaLabel="Category description" placeholder="Describe this category and the products customers will find here." minHeight="sm" /></div><div className={labelClass}><span className="inline-flex items-center gap-1">Additional description<Help label="Additional description">Optional longer content shown after the product listing, useful for buying guidance and category SEO.</Help></span><RichTextEditor value={additionalDescription} onChange={setAdditionalDescription} ariaLabel="Additional category description" placeholder="Add buying guidance, compatibility information or longer SEO content." minHeight="sm" /></div></div></section>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Images</h2><p className="mt-1 text-xs text-ink-muted">Upload a wide category cover and a compact thumbnail for menus or subcategory cards.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><FilePicker label="Category cover" hint="Recommended: wide landscape image, JPG, PNG or WebP." file={cover} setFile={setCover} /><FilePicker label="Category thumbnail" hint="Recommended: square image for navigation and cards." file={thumbnail} setFile={setThumbnail} /></div></section>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Search engine optimisation</h2><div className="mt-4 rounded-lg border border-border p-4 shadow-card"><p className="truncate text-xs text-[#202124]">ukcomputershop.co.uk › category › {slug || "category-url"}</p><p className="mt-1 truncate text-lg text-[#1a0dab]">{previewTitle}</p><p className="mt-1 line-clamp-2 text-[13px] leading-5 text-[#4d5156]">{previewDescription}</p></div><div className="mt-4 grid gap-4"><label className={labelClass}>Meta title<div className="relative"><input value={metaTitle} onChange={(event) => setMetaTitle(event.target.value)} maxLength={70} placeholder={title || "Category title"} className={`${inputClass} pr-14`} /><span className="absolute bottom-3 right-3 text-[10.5px] text-ink-muted">{metaTitle.length}/70</span></div></label><label className={labelClass}>Meta description<div className="relative"><textarea value={metaDescription} onChange={(event) => setMetaDescription(event.target.value)} maxLength={320} rows={3} className={`${inputClass} h-auto py-3 pb-7`} /><span className="absolute bottom-2.5 right-3 text-[10.5px] text-ink-muted">{metaDescription.length}/320</span></div></label><label className={labelClass}>Friendly URL<div className="mt-2 flex h-10 items-center rounded-md border border-border-strong"><span className="hidden border-r border-border px-3 text-xs text-ink-muted sm:block">/category/</span><input value={slug} onChange={(event) => setSlug(slugify(event.target.value))} className="min-w-0 flex-1 px-3 font-mono text-xs outline-none" /></div></label><label className="flex items-center gap-3 rounded-md border border-border p-3 text-[13px] font-semibold text-ink-secondary"><input type="checkbox" checked={isIndexable} onChange={(event) => setIsIndexable(event.target.checked)} className="h-4 w-4 accent-ink" />Allow search engines to index this category</label></div></section>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Hierarchy and offline behaviour</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className={labelClass}>Parent category<select value={parentId} onChange={(event) => setParentId(event.target.value)} className={inputClass}><option value="">Top level</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.title}</option>)}</select></label><label className={labelClass}>Position<input type="number" min="0" value={sortOrder} onChange={(event) => setSortOrder(event.target.value)} className={inputClass} /></label><label className={labelClass}>When category is disabled<select value={redirectBehaviour} onChange={(event) => setRedirectBehaviour(event.target.value as RedirectBehaviour)} className={inputClass}><option value="NOT_FOUND">Not found (404)</option><option value="GONE">Permanently removed (410)</option><option value="REDIRECT_CATEGORY_301">Permanent category redirect (301)</option><option value="REDIRECT_CATEGORY_302">Temporary category redirect (302)</option></select></label>{redirectBehaviour.startsWith("REDIRECT_CATEGORY") ? <label className={labelClass}>Redirect target<select value={redirectTargetId} onChange={(event) => setRedirectTargetId(event.target.value)} className={inputClass}><option value="">Use parent category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.title}</option>)}</select></label> : null}</div></section></section>
  <div className="fixed bottom-0 left-0 right-0 z-20 border-t border-border bg-surface/95 px-4 py-3 backdrop-blur lg:left-64"><div className="flex items-center justify-between"><Link href="/categories" className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-3.5 text-[13px] font-semibold text-ink-secondary"><ArrowLeft className="h-4 w-4" />Back to categories</Link><button type="submit" disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : editing ? <Save className="h-4 w-4" /> : <Check className="h-4 w-4" />}{editing ? "Save changes" : "Create category"}</button></div></div></form>;
}

function FilePicker({ label, hint, file, setFile }: { label: string; hint: string; file: File | null; setFile: (file: File | null) => void }) { return <label className="block rounded-lg border border-dashed border-border-strong bg-canvas p-4"><span className="flex items-center gap-2 text-[13px] font-semibold text-ink"><ImageIcon className="h-4 w-4 text-ink-muted" />{label}</span><span className="mt-1 block text-xs text-ink-muted">{hint}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="sr-only" /><span className="mt-4 inline-flex h-9 items-center gap-2 rounded-md border border-border bg-surface px-3 text-xs font-semibold text-ink-secondary"><Upload className="h-4 w-4" />{file ? "Change image" : "Choose image"}</span>{file ? <span className="mt-2 block truncate text-xs font-medium text-ink">{file.name}</span> : null}</label>; }
