"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Check, LoaderCircle, Star, Trash2, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { collectionFromApi } from "@/lib/api-response";

type ReviewStatus = "PENDING" | "APPROVED" | "REJECTED";
type Review = { id: number; rating: number; title: string | null; comment: string | null; status: ReviewStatus; createdAt: string; reviewerName: string | null; product: { id: number; title: string }; user: { firstName: string; lastName: string; email: string } | null };
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
const statusTone: Record<ReviewStatus, string> = { PENDING: "bg-accent-tint text-accent-tint-ink", APPROVED: "bg-positive-tint text-positive-tint-ink", REJECTED: "bg-danger-tint text-danger-tint-ink" };

export function ReviewsListing() {
  const [items, setItems] = useState<Review[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [statusFilter, setStatusFilter] = useState<"ALL" | ReviewStatus>("PENDING");
  const [mutatingId, setMutatingId] = useState<number | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Review | null>(null), [deleting, setDeleting] = useState(false);

  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: "1", perPage: "100" }); if (statusFilter !== "ALL") params.set("status", statusFilter); const response = await fetch(`/api/reviews?${params}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(apiMessage(payload, "Reviews could not be loaded.")); setItems(collectionFromApi<Review>(payload)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Reviews could not be loaded."); } finally { setLoading(false); } }, [statusFilter]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  async function approve(review: Review) { setMutatingId(review.id); setError(""); try { const response = await fetch(`/api/reviews/${review.id}/approve`, { method: "PATCH" }); if (!response.ok) throw new Error(apiMessage(await response.json().catch(() => ({})), "Review could not be approved.")); await load(); } catch (approveError) { setError(approveError instanceof Error ? approveError.message : "Review could not be approved."); } finally { setMutatingId(null); } }
  async function reject(review: Review) { setMutatingId(review.id); setError(""); try { const response = await fetch(`/api/reviews/${review.id}/reject`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }); if (!response.ok) throw new Error(apiMessage(await response.json().catch(() => ({})), "Review could not be rejected.")); await load(); } catch (rejectError) { setError(rejectError instanceof Error ? rejectError.message : "Review could not be rejected."); } finally { setMutatingId(null); } }
  async function remove() { if (!deleteTarget) return; setDeleting(true); try { const response = await fetch(`/api/reviews/${deleteTarget.id}`, { method: "DELETE" }); if (!response.ok && response.status !== 204) throw new Error(apiMessage(await response.json().catch(() => ({})), "Review could not be deleted.")); setDeleteTarget(null); await load(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Review could not be deleted."); } finally { setDeleting(false); } }

  const pendingCount = items.filter((item) => item.status === "PENDING").length;

  return <div className="w-full"><h1 className="text-[22px] font-semibold tracking-[-0.01em] text-ink">Reviews</h1><p className="mt-1 text-[13.5px] text-ink-muted">Moderate customer product reviews before they go live on the storefront.</p>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <div className="mt-5 flex gap-1 border-b border-border">{([{ id: "PENDING", label: `Pending${pendingCount ? ` (${pendingCount})` : ""}` }, { id: "APPROVED", label: "Approved" }, { id: "REJECTED", label: "Rejected" }, { id: "ALL", label: "All" }] as const).map((item) => <button key={item.id} type="button" onClick={() => setStatusFilter(item.id)} className={`relative px-3 py-2.5 text-[13px] font-semibold ${statusFilter === item.id ? "text-ink after:absolute after:inset-x-1 after:bottom-0 after:h-0.5 after:bg-ink" : "text-ink-muted hover:text-ink"}`}>{item.label}</button>)}</div>
  {loading ? <div className="flex min-h-40 items-center justify-center"><LoaderCircle className="h-5 w-5 animate-spin text-ink-muted" /></div> : <div className="mt-4 space-y-3">{items.map((review) => <div key={review.id} className="rounded-xl border border-border bg-surface p-4 shadow-card"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex items-center gap-2"><div className="flex items-center gap-0.5 text-amber-500">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className={`h-3.5 w-3.5 ${i < review.rating ? "fill-current" : "text-neutral-tint"}`} />)}</div><span className={`inline-flex rounded-full px-2 py-0.5 text-[10.5px] font-semibold ${statusTone[review.status]}`}>{review.status}</span></div><p className="mt-1.5 text-[13px] font-semibold text-ink">{review.title ?? "(no title)"}</p><p className="mt-1 text-xs leading-5 text-ink-secondary">{review.comment ?? "No comment left."}</p><p className="mt-2 text-[11px] text-ink-muted">{review.product.title} · {review.reviewerName ?? (review.user ? `${review.user.firstName} ${review.user.lastName}` : "Anonymous")} · {new Date(review.createdAt).toLocaleDateString("en-GB")}</p></div><div className="flex shrink-0 gap-2">{review.status !== "APPROVED" ? <button type="button" onClick={() => void approve(review)} disabled={mutatingId === review.id} aria-label="Approve review" className="inline-flex h-8 items-center gap-1.5 rounded-md border border-border px-2.5 text-xs font-semibold text-positive-tint-ink hover:bg-positive-tint disabled:opacity-50">{mutatingId === review.id ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5" />}Approve</button> : null}{review.status !== "REJECTED" ? <button type="button" onClick={() => void reject(review)} disabled={mutatingId === review.id} aria-label="Reject review" className="inline-flex h-8 items-center gap-1.5 rounded-md border border-border px-2.5 text-xs font-semibold text-danger-tint-ink hover:bg-danger-tint disabled:opacity-50"><X className="h-3.5 w-3.5" />Reject</button> : null}<button type="button" onClick={() => setDeleteTarget(review)} aria-label="Delete review" className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted hover:bg-danger-tint hover:text-danger-tint-ink"><Trash2 className="h-4 w-4" /></button></div></div></div>)}{!items.length ? <p className="rounded-xl border border-border bg-surface p-10 text-center text-[13px] text-ink-muted shadow-card">No reviews in this view.</p> : null}</div>}
  <Dialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null); }}><DialogContent><DialogHeader><DialogTitle>Delete review?</DialogTitle><DialogDescription>This permanently removes the review.</DialogDescription></DialogHeader><DialogFooter><button type="button" onClick={() => setDeleteTarget(null)} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="button" onClick={() => void remove()} disabled={deleting} className="inline-flex h-9 items-center gap-2 rounded-md bg-danger px-4 text-xs font-semibold text-white disabled:opacity-50">{deleting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />}Delete</button></DialogFooter></DialogContent></Dialog>
  </div>;
}
