"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, ChevronRight, LoaderCircle, Percent, Plus } from "lucide-react";
import { collectionFromApi } from "@/lib/api-response";

type TaxRate = { id: number; title: string; ratePercent: string; isDefault: boolean; status: "ACTIVE" | "INACTIVE" };
const inputClass = "h-9 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }

export function TaxRatesListing() {
  const [items, setItems] = useState<TaxRate[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [title, setTitle] = useState(""), [ratePercent, setRatePercent] = useState(""), [isDefault, setIsDefault] = useState(false), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/tax-rates", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(apiMessage(payload, "Tax rates could not be loaded.")); setItems(collectionFromApi<TaxRate>(payload)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Tax rates could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || !ratePercent) return; setSaving(true); setError(""); try { const response = await fetch("/api/tax-rates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), ratePercent: Number(ratePercent), isDefault }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Tax rate could not be created.")); setTitle(""); setRatePercent(""); setIsDefault(false); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Tax rate could not be created."); } finally { setSaving(false); } }

  return <div className="w-full max-w-2xl"><nav className="flex items-center gap-1.5 text-xs text-ink-muted"><span>Catalog</span><ChevronRight className="h-3.5 w-3.5" /><span>Tax rates</span></nav><h1 className="mt-2 text-[22px] font-semibold tracking-[-0.01em] text-ink">Tax rates</h1><p className="mt-1 text-[13.5px] text-ink-muted">VAT and other tax rates available to apply against products.</p>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <form onSubmit={(event) => void submit(event)} className="mt-5 flex flex-col gap-3 rounded-xl border border-border bg-surface p-4 shadow-card sm:flex-row sm:items-end"><label className="flex-1 text-[13px] font-semibold text-ink-secondary">Name<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. UK Standard VAT" className={`mt-2 ${inputClass}`} /></label><label className="w-32 text-[13px] font-semibold text-ink-secondary">Rate %<input type="number" min="0" max="100" step="0.01" value={ratePercent} onChange={(event) => setRatePercent(event.target.value)} className={`mt-2 ${inputClass}`} /></label><label className="flex h-9 items-center gap-2 text-[13px] font-semibold text-ink-secondary"><input type="checkbox" checked={isDefault} onChange={(event) => setIsDefault(event.target.checked)} className="h-4 w-4 rounded border-border-strong" />Default</label><button type="submit" disabled={saving || !title.trim() || !ratePercent} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Add</button></form>
  <section className="mt-5 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><table className="w-full text-left"><thead className="bg-canvas text-[10.5px] uppercase tracking-[0.06em] text-ink-muted"><tr><th className="px-4 py-3 font-semibold">Name</th><th className="px-4 py-3 text-right font-semibold">Rate</th><th className="px-4 py-3 text-center font-semibold">Default</th><th className="px-4 py-3 text-center font-semibold">Status</th></tr></thead><tbody className="divide-y divide-border">{loading ? <tr><td colSpan={4} className="h-32 text-center"><LoaderCircle className="mx-auto h-5 w-5 animate-spin text-ink-muted" /></td></tr> : items.map((item) => <tr key={item.id} className="hover:bg-canvas"><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><Percent className="h-3.5 w-3.5" /></span><span className="text-[13px] font-semibold text-ink">{item.title}</span></div></td><td className="px-4 py-3 text-right text-xs font-semibold text-ink">{Number(item.ratePercent).toFixed(2)}%</td><td className="px-4 py-3 text-center">{item.isDefault ? <span className="inline-flex rounded-full bg-accent-tint px-2 py-0.5 text-[10.5px] font-semibold text-accent-tint-ink">Default</span> : null}</td><td className="px-4 py-3 text-center"><span className={`inline-flex rounded-full px-2 py-0.5 text-[10.5px] font-semibold ${item.status === "ACTIVE" ? "bg-positive-tint text-positive-tint-ink" : "bg-neutral-tint text-ink-muted"}`}>{item.status}</span></td></tr>)}{!loading && !items.length ? <tr><td colSpan={4} className="h-32 text-center text-[13px] text-ink-muted">No tax rates yet.</td></tr> : null}</tbody></table></section></div>;
}
