"use client";

import { CURRENCY } from "@/lib/currency";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ChevronLeft, ChevronRight, Gift, LoaderCircle, Plus, Search, SlidersHorizontal } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { collectionFromApi } from "@/lib/api-response";

type GiftCardStatus = "ACTIVE" | "REDEEMED" | "EXPIRED" | "DISABLED";
type GiftCard = { id: number; code: string; initialBalance: string; currentBalance: string; currency: string; issuedToEmail: string | null; expiresAt: string | null; status: GiftCardStatus; createdAt: string };
const inputClass = "mt-2 h-10 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
const statusTone: Record<GiftCardStatus, string> = { ACTIVE: "bg-positive-tint text-positive-tint-ink", REDEEMED: "bg-neutral-tint text-ink-muted", EXPIRED: "bg-danger-tint text-danger-tint-ink", DISABLED: "bg-danger-tint text-danger-tint-ink" };
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
function money(amount: string, currency: string) { return new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(Number(amount)); }

export function GiftCardsListing() {
  const [items, setItems] = useState<GiftCard[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [query, setQuery] = useState(""), [statusFilter, setStatusFilter] = useState("ALL");
  const [page, setPage] = useState(1);
  const [creating, setCreating] = useState(false), [adjusting, setAdjusting] = useState<GiftCard | null>(null);
  const perPage = 20;
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/gift-cards?page=1&perPage=100", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(apiMessage(payload, "Gift cards could not be loaded.")); setItems(collectionFromApi<GiftCard>(payload)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Gift cards could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const visible = useMemo(() => { const term = query.trim().toLowerCase(); return items.filter((item) => (statusFilter === "ALL" || item.status === statusFilter) && (!term || item.code.toLowerCase().includes(term) || (item.issuedToEmail ?? "").toLowerCase().includes(term))); }, [items, query, statusFilter]);
  const totalPages = Math.max(1, Math.ceil(visible.length / perPage));
  const currentPage = Math.min(page, totalPages);
  const paginated = visible.slice((currentPage - 1) * perPage, currentPage * perPage);
  const activeBalance = items.filter((item) => item.status === "ACTIVE").reduce((sum, item) => sum + Number(item.currentBalance), 0);

  return <div className="w-full"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-[22px] font-semibold tracking-[-0.01em] text-ink">Gift cards</h1><p className="mt-1 text-[13.5px] text-ink-muted">Issue and manage store gift card balances.</p></div><button type="button" onClick={() => setCreating(true)} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white hover:bg-[#1d2939]"><Plus className="h-4 w-4" />Issue gift card</button></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Active balance" value={new Intl.NumberFormat("en-GB", { style: "currency", currency: CURRENCY }).format(activeBalance)} detail={`${items.filter((item) => item.status === "ACTIVE").length} active cards`} /><Metric label="Redeemed" value={String(items.filter((item) => item.status === "REDEEMED").length)} detail="Fully used" /><Metric label="Total issued" value={String(items.length)} detail="All time" /></div>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <section className="mt-5 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-[13.5px] font-semibold text-ink">Gift cards ({visible.length})</h2><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-faint" /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search code or email" className="h-9 w-full rounded-md border border-border-strong pl-9 pr-3 text-xs outline-none focus:border-accent-strong sm:w-64" /></label><label className="relative"><SlidersHorizontal className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-ink-faint" /><select value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1); }} className="h-9 rounded-md border border-border-strong bg-surface pl-8 pr-3 text-xs text-ink-secondary outline-none"><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="REDEEMED">Redeemed</option><option value="EXPIRED">Expired</option><option value="DISABLED">Disabled</option></select></label></div></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="bg-canvas text-[10.5px] uppercase tracking-[0.06em] text-ink-muted"><tr><th className="px-4 py-3 font-semibold">Code</th><th className="px-4 py-3 font-semibold">Issued to</th><th className="px-4 py-3 text-right font-semibold">Balance</th><th className="px-4 py-3 font-semibold">Expires</th><th className="px-4 py-3 text-center font-semibold">Status</th><th className="px-4 py-3 text-right font-semibold">Actions</th></tr></thead><tbody className="divide-y divide-border">{loading ? <tr><td colSpan={6} className="h-40 text-center"><LoaderCircle className="mx-auto h-5 w-5 animate-spin text-ink-muted" /></td></tr> : paginated.map((item) => <tr key={item.id} className="hover:bg-canvas"><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><Gift className="h-3.5 w-3.5" /></span><span className="font-mono text-xs font-semibold text-ink">{item.code}</span></div></td><td className="px-4 py-3 text-xs text-ink-secondary">{item.issuedToEmail ?? "—"}</td><td className="px-4 py-3 text-right text-xs font-semibold text-ink">{money(item.currentBalance, item.currency)}<span className="ml-1 text-ink-faint">/ {money(item.initialBalance, item.currency)}</span></td><td className="px-4 py-3 text-xs text-ink-secondary">{item.expiresAt ? new Date(item.expiresAt).toLocaleDateString("en-GB") : "No expiry"}</td><td className="px-4 py-3 text-center"><span className={`inline-flex rounded-full px-2 py-0.5 text-[10.5px] font-semibold ${statusTone[item.status]}`}>{item.status}</span></td><td className="px-4 py-3 text-right"><button type="button" onClick={() => setAdjusting(item)} className="h-8 rounded-md border border-border px-3 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint">Adjust</button></td></tr>)}{!loading && !paginated.length ? <tr><td colSpan={6} className="h-40 text-center text-[13px] text-ink-muted">No gift cards found.</td></tr> : null}</tbody></table></div>
  {totalPages > 1 ? <div className="flex items-center justify-between border-t border-border px-4 py-3"><p className="text-xs text-ink-muted">Page {currentPage} of {totalPages}</p><div className="flex gap-2"><button type="button" disabled={currentPage <= 1} onClick={() => setPage((value) => value - 1)} className="inline-flex h-9 items-center gap-1 rounded-md border border-border px-3 text-xs font-semibold text-ink-secondary disabled:opacity-45"><ChevronLeft className="h-4 w-4" />Previous</button><button type="button" disabled={currentPage >= totalPages} onClick={() => setPage((value) => value + 1)} className="inline-flex h-9 items-center gap-1 rounded-md border border-border px-3 text-xs font-semibold text-ink-secondary disabled:opacity-45">Next<ChevronRight className="h-4 w-4" /></button></div></div> : null}
  </section>
  {creating ? <IssueDialog onClose={() => setCreating(false)} onSaved={load} /> : null}
  {adjusting ? <AdjustDialog giftCard={adjusting} onClose={() => setAdjusting(null)} onSaved={load} /> : null}
  </div>;
}

function IssueDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) {
  const [initialBalance, setInitialBalance] = useState(""), [issuedToEmail, setIssuedToEmail] = useState(""), [expiresAt, setExpiresAt] = useState(""), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/gift-cards", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ initialBalance: Number(initialBalance), issuedToEmail: issuedToEmail.trim() || undefined, expiresAt: expiresAt || undefined }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Gift card could not be issued.")); onClose(); await onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Gift card could not be issued."); } finally { setSaving(false); } }
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Issue gift card</DialogTitle><DialogDescription>A unique code is generated automatically.</DialogDescription></DialogHeader><form onSubmit={(event) => void submit(event)}>{error ? <div role="alert" className="mb-3 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}<label className="text-[13px] font-semibold text-ink-secondary">Balance ({CURRENCY})<input type="number" min="0.01" step="0.01" required value={initialBalance} onChange={(event) => setInitialBalance(event.target.value)} className={inputClass} /></label><label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Issued to (optional)<input type="email" value={issuedToEmail} onChange={(event) => setIssuedToEmail(event.target.value)} placeholder="customer@example.com" className={inputClass} /></label><label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Expires (optional)<input type="date" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} className={inputClass} /></label><DialogFooter className="mt-4"><button type="button" onClick={onClose} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="submit" disabled={saving || !initialBalance} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Issue</button></DialogFooter></form></DialogContent></Dialog>;
}

function AdjustDialog({ giftCard, onClose, onSaved }: { giftCard: GiftCard; onClose: () => void; onSaved: () => Promise<void> }) {
  const [adjustment, setAdjustment] = useState(""), [status, setStatus] = useState<GiftCardStatus>(giftCard.status), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const body: Record<string, unknown> = {}; if (adjustment) body.adjustment = Number(adjustment); if (status !== giftCard.status) body.status = status; const response = await fetch(`/api/gift-cards/${giftCard.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Gift card could not be updated.")); onClose(); await onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Gift card could not be updated."); } finally { setSaving(false); } }
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Adjust {giftCard.code}</DialogTitle><DialogDescription>Current balance {money(giftCard.currentBalance, giftCard.currency)}</DialogDescription></DialogHeader><form onSubmit={(event) => void submit(event)}>{error ? <div role="alert" className="mb-3 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}<label className="text-[13px] font-semibold text-ink-secondary">Balance adjustment<input type="number" step="0.01" value={adjustment} onChange={(event) => setAdjustment(event.target.value)} placeholder="e.g. -10.00 or 5.00" className={inputClass} /></label><label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Status<select value={status} onChange={(event) => setStatus(event.target.value as GiftCardStatus)} className={inputClass}><option value="ACTIVE">Active</option><option value="REDEEMED">Redeemed</option><option value="EXPIRED">Expired</option><option value="DISABLED">Disabled</option></select></label><DialogFooter className="mt-4"><button type="button" onClick={onClose} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="submit" disabled={saving || (!adjustment && status === giftCard.status)} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Save</button></DialogFooter></form></DialogContent></Dialog>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-xl border border-border bg-surface p-4 shadow-card"><p className="text-[10.5px] font-semibold uppercase tracking-[0.06em] text-ink-muted">{label}</p><p className="mt-2 text-lg font-semibold text-ink">{value}</p><p className="mt-1 text-xs text-ink-muted">{detail}</p></div>; }
