"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, LayoutPanelTop, LoaderCircle, Menu as MenuIcon, Pencil, Plus, Trash2 } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { collectionFromApi } from "@/lib/api-response";

type Status = "ACTIVE" | "INACTIVE";
type MegaMenuLink = { id?: number; label: string; categoryId?: number; href?: string; sortOrder?: number };
type MegaMenuColumn = { id?: number; title?: string; sortOrder?: number; links: MegaMenuLink[] };
type MenuItem = { id: number; parentId: number | null; label: string; href: string | null; categoryId: number | null; sortOrder: number; status: Status; megaMenuPanel: { columns: MegaMenuColumn[] } | null };
type Menu = { id: number; name: string; slug: string; location: "HEADER" | "FOOTER"; status: Status; items: MenuItem[] };
const inputClass = "mt-2 h-10 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }

export function MenusListing() {
  const [menus, setMenus] = useState<Menu[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [name, setName] = useState(""), [slug, setSlug] = useState(""), [location, setLocation] = useState<"HEADER" | "FOOTER">("HEADER"), [creatingMenu, setCreatingMenu] = useState(false);
  const [itemEditing, setItemEditing] = useState<MenuItem | "new" | null>(null);
  const [panelEditing, setPanelEditing] = useState<MenuItem | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<MenuItem | null>(null), [deleting, setDeleting] = useState(false);

  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/menus", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(apiMessage(payload, "Menus could not be loaded.")); const list = collectionFromApi<Menu>(payload); setMenus(list); setSelectedId((current) => current && list.some((menu) => menu.id === current) ? current : (list[0]?.id ?? null)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Menus could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const selected = menus.find((menu) => menu.id === selectedId) ?? null;

  async function createMenu(event: FormEvent) { event.preventDefault(); if (!name.trim() || !slug.trim()) return; setCreatingMenu(true); setError(""); try { const response = await fetch("/api/menus", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), slug: slug.trim(), location }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Menu could not be created.")); setName(""); setSlug(""); await load(); } catch (createError) { setError(createError instanceof Error ? createError.message : "Menu could not be created."); } finally { setCreatingMenu(false); } }
  async function removeItem() { if (!deleteTarget || !selected) return; setDeleting(true); try { const response = await fetch(`/api/menus/${selected.id}/items/${deleteTarget.id}`, { method: "DELETE" }); if (!response.ok && response.status !== 204) throw new Error(apiMessage(await response.json().catch(() => ({})), "Menu item could not be deleted.")); setDeleteTarget(null); await load(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Menu item could not be deleted."); } finally { setDeleting(false); } }

  return <div className="w-full"><h1 className="text-[22px] font-semibold tracking-[-0.01em] text-ink">Menus</h1><p className="mt-1 text-[13.5px] text-ink-muted">Header and footer navigation, including mega-menu panels.</p>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <div className="mt-5 grid gap-5 lg:grid-cols-[280px_1fr]">
    <div>
      <div className="overflow-hidden rounded-xl border border-border bg-surface shadow-card">{loading ? <div className="p-6 text-center"><LoaderCircle className="mx-auto h-5 w-5 animate-spin text-ink-muted" /></div> : <ul className="divide-y divide-border">{menus.map((menu) => <li key={menu.id}><button type="button" onClick={() => setSelectedId(menu.id)} className={`flex w-full items-center gap-2.5 p-3.5 text-left ${selectedId === menu.id ? "bg-canvas" : "hover:bg-canvas/60"}`}><MenuIcon className="h-4 w-4 shrink-0 text-ink-muted" /><span className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-ink">{menu.name}</p><p className="mt-0.5 text-[10.5px] text-ink-muted">{menu.location} · {menu.items.length} items</p></span></button></li>)}{!menus.length ? <li className="p-6 text-center text-[13px] text-ink-muted">No menus yet.</li> : null}</ul>}</div>
      <form onSubmit={(event) => void createMenu(event)} className="mt-3 rounded-xl border border-border bg-surface p-3.5 shadow-card"><p className="text-[11px] font-semibold uppercase tracking-[0.06em] text-ink-muted">New menu</p><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Name" className={inputClass} /><input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="slug" className={`${inputClass} font-mono`} /><select value={location} onChange={(event) => setLocation(event.target.value as "HEADER" | "FOOTER")} className={inputClass}><option value="HEADER">Header</option><option value="FOOTER">Footer</option></select><button type="submit" disabled={creatingMenu || !name.trim() || !slug.trim()} className="mt-3 inline-flex h-9 w-full items-center justify-center gap-2 rounded-md bg-ink text-[13px] font-semibold text-white disabled:opacity-50">{creatingMenu ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Add menu</button></form>
    </div>
    <section className="overflow-hidden rounded-xl border border-border bg-surface shadow-card">{!selected ? <p className="p-8 text-center text-[13px] text-ink-muted">Select or create a menu to manage its items.</p> : <>
      <div className="flex items-center justify-between border-b border-border p-4"><div><h2 className="text-[14px] font-semibold text-ink">{selected.name}</h2><p className="mt-0.5 text-xs text-ink-muted">{selected.location.toLowerCase()} navigation</p></div><button type="button" onClick={() => setItemEditing("new")} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-3.5 text-xs font-semibold text-white hover:bg-[#1d2939]"><Plus className="h-4 w-4" />Add item</button></div>
      <div className="divide-y divide-border">{selected.items.map((item) => <div key={item.id} className="flex items-center gap-3 p-3.5" style={{ paddingLeft: item.parentId ? "2.5rem" : "0.875rem" }}><div className="min-w-0 flex-1"><p className="text-[13px] font-semibold text-ink">{item.label}</p><p className="mt-0.5 truncate text-xs text-ink-muted">{item.categoryId ? `Category #${item.categoryId}` : item.href ?? "—"}</p></div><span className={`inline-flex rounded-full px-2 py-0.5 text-[10.5px] font-semibold ${item.status === "ACTIVE" ? "bg-positive-tint text-positive-tint-ink" : "bg-neutral-tint text-ink-muted"}`}>{item.status}</span><button type="button" onClick={() => setPanelEditing(item)} className="inline-flex h-8 items-center gap-1.5 rounded-md border border-border px-2.5 text-xs font-semibold text-ink-secondary hover:bg-neutral-tint"><LayoutPanelTop className="h-3.5 w-3.5" />{item.megaMenuPanel ? "Edit panel" : "Add panel"}</button><button type="button" onClick={() => setItemEditing(item)} aria-label={`Edit ${item.label}`} className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted hover:bg-neutral-tint hover:text-ink"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setDeleteTarget(item)} aria-label={`Delete ${item.label}`} className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted hover:bg-danger-tint hover:text-danger-tint-ink"><Trash2 className="h-4 w-4" /></button></div>)}{!selected.items.length ? <p className="p-8 text-center text-[13px] text-ink-muted">No items in this menu yet.</p> : null}</div>
    </>}</section>
  </div>
  {itemEditing && selected ? <ItemDialog menu={selected} item={itemEditing === "new" ? null : itemEditing} onClose={() => setItemEditing(null)} onSaved={load} /> : null}
  {panelEditing ? <PanelDialog item={panelEditing} onClose={() => setPanelEditing(null)} onSaved={load} /> : null}
  <Dialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null); }}><DialogContent><DialogHeader><DialogTitle>Delete menu item?</DialogTitle><DialogDescription>{deleteTarget ? `"${deleteTarget.label}" and any child items will be removed.` : ""}</DialogDescription></DialogHeader><DialogFooter><button type="button" onClick={() => setDeleteTarget(null)} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="button" onClick={() => void removeItem()} disabled={deleting} className="inline-flex h-9 items-center gap-2 rounded-md bg-danger px-4 text-xs font-semibold text-white disabled:opacity-50">{deleting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />}Delete</button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function ItemDialog({ menu, item, onClose, onSaved }: { menu: Menu; item: MenuItem | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [label, setLabel] = useState(item?.label ?? ""), [href, setHref] = useState(item?.href ?? "");
  const [categoryId, setCategoryId] = useState(item?.categoryId != null ? String(item.categoryId) : "");
  const [parentId, setParentId] = useState(item?.parentId != null ? String(item.parentId) : "");
  const [status, setStatus] = useState<Status>(item?.status ?? "ACTIVE"), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const parentOptions = menu.items.filter((candidate) => candidate.id !== item?.id && !candidate.parentId);
  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError("");
    const body = { label: label.trim(), href: href.trim() || undefined, categoryId: categoryId ? Number(categoryId) : undefined, parentId: parentId ? Number(parentId) : undefined, status };
    try { const response = await fetch(item ? `/api/menus/${menu.id}/items/${item.id}` : `/api/menus/${menu.id}/items`, { method: item ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Menu item could not be saved.")); onClose(); await onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Menu item could not be saved."); } finally { setSaving(false); }
  }
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>{item ? "Edit menu item" : "Add menu item"}</DialogTitle><DialogDescription>{menu.name}</DialogDescription></DialogHeader><form onSubmit={(event) => void submit(event)}>{error ? <div role="alert" className="mb-3 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}<label className="text-[13px] font-semibold text-ink-secondary">Label<input required value={label} onChange={(event) => setLabel(event.target.value)} className={inputClass} /></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[13px] font-semibold text-ink-secondary">Link URL<input value={href} onChange={(event) => setHref(event.target.value)} className={inputClass} /></label><label className="text-[13px] font-semibold text-ink-secondary">or Category ID<input value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className={inputClass} /></label></div><label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Parent item (optional)<select value={parentId} onChange={(event) => setParentId(event.target.value)} className={inputClass}><option value="">Top level</option>{parentOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label className="mt-4 block text-[13px] font-semibold text-ink-secondary">Status<select value={status} onChange={(event) => setStatus(event.target.value as Status)} className={inputClass}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><DialogFooter className="mt-4"><button type="button" onClick={onClose} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="submit" disabled={saving || !label.trim()} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Save</button></DialogFooter></form></DialogContent></Dialog>;
}

function PanelDialog({ item, onClose, onSaved }: { item: MenuItem; onClose: () => void; onSaved: () => Promise<void> }) {
  const [columns, setColumns] = useState<MegaMenuColumn[]>(item.megaMenuPanel?.columns.length ? item.megaMenuPanel.columns : [{ title: "", links: [{ label: "" }] }]);
  const [saving, setSaving] = useState(false), [error, setError] = useState("");
  function addColumn() { setColumns((current) => [...current, { title: "", links: [{ label: "" }] }]); }
  function removeColumn(index: number) { setColumns((current) => current.filter((_, i) => i !== index)); }
  function updateColumn(index: number, title: string) { setColumns((current) => current.map((column, i) => i === index ? { ...column, title } : column)); }
  function addLink(columnIndex: number) { setColumns((current) => current.map((column, i) => i === columnIndex ? { ...column, links: [...column.links, { label: "" }] } : column)); }
  function removeLink(columnIndex: number, linkIndex: number) { setColumns((current) => current.map((column, i) => i === columnIndex ? { ...column, links: column.links.filter((_, li) => li !== linkIndex) } : column)); }
  function updateLink(columnIndex: number, linkIndex: number, patch: Partial<MegaMenuLink>) { setColumns((current) => current.map((column, i) => i === columnIndex ? { ...column, links: column.links.map((link, li) => li === linkIndex ? { ...link, ...patch } : link) } : column)); }
  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError("");
    const body = { columns: columns.map((column) => ({ title: column.title || undefined, links: column.links.filter((link) => link.label.trim()).map((link) => ({ label: link.label.trim(), categoryId: link.categoryId ? Number(link.categoryId) : undefined, href: link.href || undefined })) })).filter((column) => column.links.length) };
    try { const response = await fetch(`/api/menus/items/${item.id}/mega-menu-panel`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Mega menu panel could not be saved.")); onClose(); await onSaved(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Mega menu panel could not be saved."); } finally { setSaving(false); }
  }
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Mega menu panel — {item.label}</DialogTitle><DialogDescription>Columns of links shown when this item is hovered.</DialogDescription></DialogHeader><form onSubmit={(event) => void submit(event)}>{error ? <div role="alert" className="mb-3 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <div className="max-h-[50vh] space-y-4 overflow-y-auto pr-1">{columns.map((column, columnIndex) => <div key={columnIndex} className="rounded-lg border border-border p-3"><div className="flex items-center gap-2"><input value={column.title ?? ""} onChange={(event) => updateColumn(columnIndex, event.target.value)} placeholder="Column title" className="h-9 flex-1 rounded-md border border-border-strong bg-surface px-2.5 text-xs outline-none focus:border-accent-strong" />{columns.length > 1 ? <button type="button" onClick={() => removeColumn(columnIndex)} aria-label="Remove column" className="flex h-8 w-8 items-center justify-center rounded-md text-ink-muted hover:bg-danger-tint hover:text-danger-tint-ink"><Trash2 className="h-4 w-4" /></button> : null}</div><div className="mt-2 space-y-2">{column.links.map((link, linkIndex) => <div key={linkIndex} className="flex items-center gap-1.5"><input value={link.label} onChange={(event) => updateLink(columnIndex, linkIndex, { label: event.target.value })} placeholder="Link label" className="h-8 w-32 rounded-md border border-border-strong bg-surface px-2 text-xs outline-none focus:border-accent-strong" /><input value={link.href ?? ""} onChange={(event) => updateLink(columnIndex, linkIndex, { href: event.target.value })} placeholder="URL" className="h-8 flex-1 rounded-md border border-border-strong bg-surface px-2 text-xs outline-none focus:border-accent-strong" /><input value={link.categoryId ?? ""} onChange={(event) => updateLink(columnIndex, linkIndex, { categoryId: event.target.value ? Number(event.target.value) : undefined })} placeholder="or Category ID" className="h-8 w-28 rounded-md border border-border-strong bg-surface px-2 text-xs outline-none focus:border-accent-strong" /><button type="button" onClick={() => removeLink(columnIndex, linkIndex)} aria-label="Remove link" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-ink-muted hover:bg-danger-tint hover:text-danger-tint-ink"><Trash2 className="h-3.5 w-3.5" /></button></div>)}</div><button type="button" onClick={() => addLink(columnIndex)} className="mt-2 inline-flex items-center gap-1.5 text-xs font-semibold text-ink-secondary hover:text-ink"><Plus className="h-3.5 w-3.5" />Add link</button></div>)}</div>
  <button type="button" onClick={addColumn} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-ink-secondary hover:text-ink"><Plus className="h-3.5 w-3.5" />Add column</button>
  <DialogFooter className="mt-4"><button type="button" onClick={onClose} className="h-9 rounded-md border border-border px-4 text-xs font-semibold text-ink-secondary">Cancel</button><button type="submit" disabled={saving} className="inline-flex h-9 items-center gap-2 rounded-md bg-ink px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Save panel</button></DialogFooter></form></DialogContent></Dialog>;
}
