"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, ChevronRight, LoaderCircle, Newspaper, Plus } from "lucide-react";
import { collectionFromApi } from "@/lib/api-response";

type Category = { id: number; title: string; slug: string; sortOrder: number; status: "ACTIVE" | "INACTIVE" };
const inputClass = "h-9 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

export function BlogCategoriesListing() {
  const [items, setItems] = useState<Category[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [title, setTitle] = useState(""), [slug, setSlug] = useState(""), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/blog/categories", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(apiMessage(payload, "Blog categories could not be loaded.")); setItems(collectionFromApi<Category>(payload)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Blog categories could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  function updateTitle(value: string) { const generated = slugify(title); setTitle(value); if (!slug || slug === generated) setSlug(slugify(value)); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || !slug.trim()) return; setSaving(true); setError(""); try { const response = await fetch("/api/blog/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), slug: slug.trim(), sortOrder: items.length }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Category could not be created.")); setTitle(""); setSlug(""); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Category could not be created."); } finally { setSaving(false); } }

  return <div className="w-full max-w-2xl"><nav className="flex items-center gap-1.5 text-xs text-ink-muted"><Link href="/blog" className="hover:text-ink">Blog</Link><ChevronRight className="h-3.5 w-3.5" /><span>Categories</span></nav><h1 className="mt-2 text-[22px] font-semibold tracking-[-0.01em] text-ink">Blog categories</h1><p className="mt-1 text-[13.5px] text-ink-muted">Group blog posts for the storefront blog&apos;s category filter.</p>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <form onSubmit={(event) => void submit(event)} className="mt-5 flex flex-col gap-3 rounded-xl border border-border bg-surface p-4 shadow-card sm:flex-row sm:items-end"><label className="flex-1 text-[13px] font-semibold text-ink-secondary">Name<input value={title} onChange={(event) => updateTitle(event.target.value)} placeholder="e.g. Buying guides" className={`mt-2 ${inputClass}`} /></label><label className="flex-1 text-[13px] font-semibold text-ink-secondary">Slug<input value={slug} onChange={(event) => setSlug(slugify(event.target.value))} className={`mt-2 font-mono text-xs ${inputClass}`} /></label><button type="submit" disabled={saving || !title.trim() || !slug.trim()} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Add</button></form>
  <section className="mt-5 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><table className="w-full text-left"><thead className="bg-canvas text-[10.5px] uppercase tracking-[0.06em] text-ink-muted"><tr><th className="px-4 py-3 font-semibold">Name</th><th className="px-4 py-3 font-semibold">Slug</th></tr></thead><tbody className="divide-y divide-border">{loading ? <tr><td colSpan={2} className="h-32 text-center"><LoaderCircle className="mx-auto h-5 w-5 animate-spin text-ink-muted" /></td></tr> : items.map((item) => <tr key={item.id} className="hover:bg-canvas"><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><Newspaper className="h-3.5 w-3.5" /></span><span className="text-[13px] font-semibold text-ink">{item.title}</span></div></td><td className="px-4 py-3 font-mono text-xs text-ink-muted">{item.slug}</td></tr>)}{!loading && !items.length ? <tr><td colSpan={2} className="h-32 text-center text-[13px] text-ink-muted">No blog categories yet.</td></tr> : null}</tbody></table></section>
  <Link href="/blog" className="mt-5 inline-flex h-9 items-center gap-2 rounded-md border border-border px-3.5 text-[13px] font-semibold text-ink-secondary hover:bg-neutral-tint"><ArrowLeft className="h-4 w-4" />Back to blog</Link></div>;
}
