"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Check, ChevronRight, LoaderCircle, Save } from "lucide-react";
import { RichTextEditor } from "@/components/ui/rich-text-editor";
import { collectionFromApi } from "@/lib/api-response";

type Option = { id: number; title?: string; name?: string };
const inputClass = "mt-2 h-10 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
const labelClass = "text-[13px] font-semibold text-ink-secondary";
function message(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

export function BlogPostFormPage({ postId }: { postId?: number }) {
  const router = useRouter(), editing = Number.isInteger(postId);
  const [categories, setCategories] = useState<Option[]>([]), [authors, setAuthors] = useState<Option[]>([]);
  const [loading, setLoading] = useState(true);
  const [title, setTitle] = useState(""), [slug, setSlug] = useState(""), [excerpt, setExcerpt] = useState(""), [content, setContent] = useState("");
  const [blogCategoryId, setBlogCategoryId] = useState(""), [authorId, setAuthorId] = useState(""), [tags, setTags] = useState("");
  const [isFeatured, setIsFeatured] = useState(false), [status, setStatus] = useState<"DRAFT" | "PUBLISHED">("DRAFT");
  const [metaTitle, setMetaTitle] = useState(""), [metaDescription, setMetaDescription] = useState("");
  const [saving, setSaving] = useState(false), [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(async () => { try { const [categoriesResponse, authorsResponse] = await Promise.all([fetch("/api/blog/categories"), fetch("/api/blog/authors")]); setCategories(collectionFromApi<Option>(await categoriesResponse.json())); setAuthors(collectionFromApi<Option>(await authorsResponse.json())); if (editing) { const response = await fetch(`/api/blog/posts/${postId}`); const payload = await response.json(); if (!response.ok) throw new Error(message(payload, "Post could not be loaded.")); const item = payload.data ?? payload; setTitle(item.title); setSlug(item.slug); setExcerpt(item.excerpt ?? ""); setContent(item.content ?? ""); setBlogCategoryId(item.blogCategoryId ? String(item.blogCategoryId) : ""); setAuthorId(item.authorId ? String(item.authorId) : ""); setTags(Array.isArray(item.tags) ? item.tags.join(", ") : ""); setIsFeatured(Boolean(item.isFeatured)); setStatus(item.status); setMetaTitle(item.metaTitle ?? ""); setMetaDescription(item.metaDescription ?? ""); } } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Post could not be loaded."); } finally { setLoading(false); } }, 0); return () => window.clearTimeout(timer); }, [postId, editing]);
  function updateTitle(value: string) { const generated = slugify(title); setTitle(value); if (!slug || slug === generated) setSlug(slugify(value)); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || !slug.trim() || !content.trim()) { setError("Title, friendly URL and content are required."); return; } setSaving(true); setError(""); try { const response = await fetch(editing ? `/api/blog/posts/${postId}` : "/api/blog/posts", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), slug: slug.trim(), excerpt: excerpt.trim() || undefined, content, blogCategoryId: blogCategoryId ? Number(blogCategoryId) : undefined, authorId: authorId ? Number(authorId) : undefined, tags: tags.trim() ? tags.split(",").map((tag) => tag.trim()).filter(Boolean) : undefined, isFeatured, status, metaTitle: metaTitle.trim() || undefined, metaDescription: metaDescription.trim() || undefined }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(message(payload, "Post could not be saved.")); router.push("/blog"); router.refresh(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Post could not be saved."); } finally { setSaving(false); } }
  if (loading) return <div className="flex min-h-80 items-center justify-center"><LoaderCircle className="h-6 w-6 animate-spin text-ink-muted" /></div>;
  return <form onSubmit={(event) => void submit(event)} className="w-full pb-20"><div><nav className="flex items-center gap-1.5 text-xs text-ink-muted"><Link href="/blog" className="hover:text-ink">Blog</Link><ChevronRight className="h-3.5 w-3.5" /><span>{editing ? "Edit post" : "Add post"}</span></nav><h1 className="mt-2 text-[22px] font-semibold text-ink">{editing ? `Edit ${title}` : "Add post"}</h1><p className="mt-1 text-[13.5px] text-ink-muted">Buying guides and news shown on the storefront blog.</p></div>
  {error ? <div role="alert" className="mt-4 flex gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <section className="mt-4 space-y-7 rounded-xl border border-border bg-surface p-5 shadow-card"><div className="grid gap-4 md:grid-cols-[1fr_220px]"><label className={labelClass}>Post title<input autoFocus={!editing} value={title} onChange={(event) => updateTitle(event.target.value)} maxLength={255} placeholder="e.g. How to choose a graphics card" className={inputClass} /></label><label className={labelClass}>Status<select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className={inputClass}><option value="PUBLISHED">Published</option><option value="DRAFT">Draft</option></select></label></div>
  <div className="grid gap-4 md:grid-cols-2"><label className={labelClass}>Category<select value={blogCategoryId} onChange={(event) => setBlogCategoryId(event.target.value)} className={inputClass}><option value="">No category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.title}</option>)}</select></label><label className={labelClass}>Author<select value={authorId} onChange={(event) => setAuthorId(event.target.value)} className={inputClass}><option value="">No author</option>{authors.map((author) => <option key={author.id} value={author.id}>{author.name}</option>)}</select></label></div>
  <label className={labelClass}>Excerpt<textarea value={excerpt} onChange={(event) => setExcerpt(event.target.value)} rows={2} placeholder="Short summary shown on blog listing cards." className={`${inputClass} h-auto resize-y py-3`} /></label>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Post content</h2><div className="mt-4"><RichTextEditor value={content} onChange={setContent} ariaLabel="Post content" placeholder="Write the post." minHeight="lg" /></div></section>
  <div className="grid gap-4 border-t border-border pt-6 md:grid-cols-2"><label className={labelClass}>Tags<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="comma, separated, tags" className={inputClass} /></label><label className="mt-7 flex items-center gap-3 text-[13px] font-semibold text-ink-secondary"><input type="checkbox" checked={isFeatured} onChange={(event) => setIsFeatured(event.target.checked)} className="h-4 w-4 accent-ink" />Feature this post</label></div>
  <section className="border-t border-border pt-6"><h2 className="text-sm font-semibold text-ink">Search engine optimisation</h2><div className="mt-4 rounded-lg border border-border p-4 shadow-card"><p className="truncate text-xs text-[#202124]">ukcomputershop.co.uk › blog › {slug || "post-url"}</p><p className="mt-1 truncate text-lg text-[#1a0dab]">{metaTitle.trim() || title || "Post title"}</p><p className="mt-1 line-clamp-2 text-[13px] leading-5 text-[#4d5156]">{metaDescription.trim() || excerpt || "Add a meta description to preview its search result."}</p></div><div className="mt-4 grid gap-4"><label className={labelClass}>Meta title<div className="relative"><input value={metaTitle} onChange={(event) => setMetaTitle(event.target.value)} maxLength={70} placeholder={title || "Post title"} className={`${inputClass} pr-14`} /><span className="absolute bottom-3 right-3 text-[10.5px] text-ink-muted">{metaTitle.length}/70</span></div></label><label className={labelClass}>Meta description<div className="relative"><textarea value={metaDescription} onChange={(event) => setMetaDescription(event.target.value)} maxLength={320} rows={3} className={`${inputClass} h-auto py-3 pb-7`} /><span className="absolute bottom-2.5 right-3 text-[10.5px] text-ink-muted">{metaDescription.length}/320</span></div></label><label className={labelClass}>Friendly URL<div className="mt-2 flex h-10 items-center rounded-md border border-border-strong"><span className="hidden border-r border-border px-3 text-xs text-ink-muted sm:block">/blog/</span><input value={slug} onChange={(event) => setSlug(slugify(event.target.value))} className="min-w-0 flex-1 px-3 font-mono text-xs outline-none" /></div></label></div></section></section>
  <div className="fixed bottom-0 left-0 right-0 z-20 border-t border-border bg-surface/95 px-4 py-3 backdrop-blur lg:left-64"><div className="flex items-center justify-between"><Link href="/blog" className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-3.5 text-[13px] font-semibold text-ink-secondary"><ArrowLeft className="h-4 w-4" />Back to blog</Link><button type="submit" disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : editing ? <Save className="h-4 w-4" /> : <Check className="h-4 w-4" />}{editing ? "Save changes" : "Create post"}</button></div></div></form>;
}
