"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, ChevronRight, LoaderCircle, Plus, User } from "lucide-react";
import { collectionFromApi } from "@/lib/api-response";

type Author = { id: number; name: string; role: string | null; status: "ACTIVE" | "INACTIVE" };
const inputClass = "h-9 w-full rounded-md border border-border-strong bg-surface px-3 text-[13px] font-normal text-ink outline-none placeholder:text-ink-faint focus:border-accent-strong";
function apiMessage(payload: unknown, fallback: string) { if (payload && typeof payload === "object" && "message" in payload) { const value = (payload as { message?: unknown }).message; if (typeof value === "string") return value; if (Array.isArray(value) && typeof value[0] === "string") return value[0]; } return fallback; }

export function BlogAuthorsListing() {
  const [items, setItems] = useState<Author[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [name, setName] = useState(""), [role, setRole] = useState(""), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/blog/authors", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(apiMessage(payload, "Authors could not be loaded.")); setItems(collectionFromApi<Author>(payload)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Authors could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; setSaving(true); setError(""); try { const response = await fetch("/api/blog/authors", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), role: role.trim() || undefined }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiMessage(payload, "Author could not be created.")); setName(""); setRole(""); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Author could not be created."); } finally { setSaving(false); } }

  return <div className="w-full max-w-2xl"><nav className="flex items-center gap-1.5 text-xs text-ink-muted"><Link href="/blog" className="hover:text-ink">Blog</Link><ChevronRight className="h-3.5 w-3.5" /><span>Authors</span></nav><h1 className="mt-2 text-[22px] font-semibold tracking-[-0.01em] text-ink">Blog authors</h1><p className="mt-1 text-[13.5px] text-ink-muted">Bylines shown on storefront blog posts.</p>
  {error ? <div role="alert" className="mt-4 flex items-start gap-2 rounded-md bg-danger-tint p-3 text-xs text-danger-tint-ink ring-1 ring-inset ring-danger-tint-border"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div> : null}
  <form onSubmit={(event) => void submit(event)} className="mt-5 flex flex-col gap-3 rounded-xl border border-border bg-surface p-4 shadow-card sm:flex-row sm:items-end"><label className="flex-1 text-[13px] font-semibold text-ink-secondary">Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Priya Shah" className={`mt-2 ${inputClass}`} /></label><label className="flex-1 text-[13px] font-semibold text-ink-secondary">Role<input value={role} onChange={(event) => setRole(event.target.value)} placeholder="e.g. Hardware editor" className={`mt-2 ${inputClass}`} /></label><button type="submit" disabled={saving || !name.trim()} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-ink px-4 text-[13px] font-semibold text-white disabled:opacity-50">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Add</button></form>
  <section className="mt-5 overflow-hidden rounded-xl border border-border bg-surface shadow-card"><table className="w-full text-left"><thead className="bg-canvas text-[10.5px] uppercase tracking-[0.06em] text-ink-muted"><tr><th className="px-4 py-3 font-semibold">Name</th><th className="px-4 py-3 font-semibold">Role</th></tr></thead><tbody className="divide-y divide-border">{loading ? <tr><td colSpan={2} className="h-32 text-center"><LoaderCircle className="mx-auto h-5 w-5 animate-spin text-ink-muted" /></td></tr> : items.map((item) => <tr key={item.id} className="hover:bg-canvas"><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-neutral-tint text-ink-muted"><User className="h-3.5 w-3.5" /></span><span className="text-[13px] font-semibold text-ink">{item.name}</span></div></td><td className="px-4 py-3 text-xs text-ink-secondary">{item.role ?? "—"}</td></tr>)}{!loading && !items.length ? <tr><td colSpan={2} className="h-32 text-center text-[13px] text-ink-muted">No authors yet.</td></tr> : null}</tbody></table></section>
  <Link href="/blog" className="mt-5 inline-flex h-9 items-center gap-2 rounded-md border border-border px-3.5 text-[13px] font-semibold text-ink-secondary hover:bg-neutral-tint"><ArrowLeft className="h-4 w-4" />Back to blog</Link></div>;
}
